// Code generated by cmd/genservice. DO NOT EDIT.

package flightbookingapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/http"

	"github.com/microbus-io/dwarf/workflow"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
)

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// WorkflowRunner executes a workflow by name with initial state, blocking until termination.
// foremanapi.Client satisfies this interface.
type WorkflowRunner interface {
	Run(ctx context.Context, workflowName string, initialState any, opts *workflow.FlowOptions) (outcome *workflow.FlowOutcome, err error)
}

// Executor runs tasks and workflows synchronously, blocking until termination.
// It is primarily intended for integration tests.
type Executor struct {
	svc         service.Publisher
	host        string
	opts        []pub.Option
	inFlow      *workflow.RawFlow
	outFlow     *workflow.Flow
	runner      WorkflowRunner
	flowOptions *workflow.FlowOptions
}

// NewExecutor creates a new executor proxy to the microservice.
func NewExecutor(caller service.Publisher) Executor {
	return Executor{svc: caller, host: Hostname}
}

// ForHost returns a copy of the executor with a different hostname to be applied to requests.
func (_c Executor) ForHost(host string) Executor {
	return Executor{svc: _c.svc, host: host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithOptions returns a copy of the executor with options to be applied to requests.
func (_c Executor) WithOptions(opts ...pub.Option) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...), inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithInputFlow returns a copy of the executor with an input flow to use for task execution.
// The input flow's state is available to the task in addition to the typed input arguments.
func (_c Executor) WithInputFlow(flow *workflow.RawFlow) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: flow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithOutputFlow returns a copy of the executor with an output flow to populate after task execution.
// The output flow captures the full flow state including control signals (Goto, Retry, Interrupt, Sleep).
func (_c Executor) WithOutputFlow(flow *workflow.Flow) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: flow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithWorkflowRunner returns a copy of the executor with a workflow runner for executing workflows.
// foremanapi.NewClient(svc) satisfies the WorkflowRunner interface.
func (_c Executor) WithWorkflowRunner(runner WorkflowRunner) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: runner, flowOptions: _c.flowOptions}
}

// WithFlowOptions returns a copy of the executor that creates workflows with the given flow options
// (priority, fairness key and weight). It has no effect on task execution.
func (_c Executor) WithFlowOptions(flowOptions *workflow.FlowOptions) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: flowOptions}
}

// Subgraph runs this microservice's workflows from inside a task body. Create it with
// NewSubgraph(flow), then call the method named after the workflow you want to invoke.
type Subgraph struct {
	flow *workflow.Flow
}

// NewSubgraph creates a subgraph client bound to the calling task's flow carrier.
func NewSubgraph(flow *workflow.Flow) Subgraph {
	return Subgraph{flow: flow}
}

// marshalTask supports task execution via the Executor.
func marshalTask(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any, inFlow *workflow.RawFlow, outFlow *workflow.Flow) (err error) {
	flow := inFlow
	if flow == nil {
		flow = workflow.NewRawFlow()
	}
	inState, err := workflow.NewState(in)
	if err != nil {
		return errors.Trace(err)
	}
	state := flow.RawState()
	err = state.Merge(inState)
	if err != nil {
		return errors.Trace(err)
	}
	flow.SetRawState(state)
	body, err := json.Marshal(flow)
	if err != nil {
		return errors.Trace(err)
	}
	u := httpx.JoinHostAndPath(host, route)
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Body(body),
		pub.ContentType("application/json"),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = json.NewDecoder(httpRes.Body).Decode(flow)
	if err != nil {
		return errors.Trace(err)
	}
	if outFlow != nil {
		*outFlow = flow.Flow
	}
	if out != nil {
		err = flow.ParseState(out)
		return errors.Trace(err)
	}
	return nil
}

// marshalWorkflow supports workflow execution via the Executor.
func marshalWorkflow(ctx context.Context, runner WorkflowRunner, flowOptions *workflow.FlowOptions, workflowURL string, in any, out any) (status string, err error) {
	outcome, err := runner.Run(ctx, workflowURL, in, flowOptions)
	if err != nil {
		if outcome != nil {
			return outcome.Status, err // No trace
		}
		return "", err // No trace
	}
	if outcome == nil {
		return "", nil
	}
	status = outcome.Status
	if out != nil {
		err = outcome.State.Parse(out)
		if err != nil {
			return status, errors.Trace(err)
		}
	}
	return status, nil
}

// marshalSubgraph runs a child workflow via the flow carrier and returns the parker's yield.
func marshalSubgraph(flow *workflow.Flow, url string, in any, out any) (yield bool, err error) {
	if flow == nil {
		return false, errors.New("Subgraph requires a flow carrier (call from a task body)")
	}
	return flow.Subgraph(url, in, out)
}

// Demo serves the human-in-the-loop demo page that drives the BookFlight workflow, presenting each proposed
// flight and resuming the parked flow with the traveler's accept or keep-searching decision.
func (_c Client) Demo(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Demo
	if method == "" {
		method = Demo.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Demo.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Demo serves the human-in-the-loop demo page that drives the BookFlight workflow, presenting each proposed
// flight and resuming the parked flow with the traveler's accept or keep-searching decision.
func (_c MulticastClient) Demo(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Demo
	if method == "" {
		method = Demo.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Demo.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// SearchFlights looks up the flights serving a route and seeds the candidate list for the workflow to propose.
func (_c Executor) SearchFlights(ctx context.Context, origin string, destination string) (candidates []Flight, flightIndex int, err error) { // MARKER: SearchFlights
	var out SearchFlightsOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, SearchFlights.Method, SearchFlights.Route, SearchFlightsIn{Origin: origin, Destination: destination}, &out, _c.inFlow, _c.outFlow)
	return out.Candidates, out.FlightIndex, err // No trace
}

// ProposeFlight selects the candidate at the current index, or marks the search exhausted when the list runs out.
func (_c Executor) ProposeFlight(ctx context.Context, candidates []Flight, flightIndex int) (currentFlight Flight, exhausted bool, err error) { // MARKER: ProposeFlight
	var out ProposeFlightOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, ProposeFlight.Method, ProposeFlight.Route, ProposeFlightIn{Candidates: candidates, FlightIndex: flightIndex}, &out, _c.inFlow, _c.outFlow)
	return out.CurrentFlight, out.Exhausted, err // No trace
}

// AwaitDecision parks the flow on a human accept/keep-searching decision for the proposed flight and advances
// to the next candidate when the traveler keeps searching.
func (_c Executor) AwaitDecision(ctx context.Context, currentFlight Flight, flightIndex int) (accepted bool, flightIndexOut int, err error) { // MARKER: AwaitDecision
	var out AwaitDecisionOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, AwaitDecision.Method, AwaitDecision.Route, AwaitDecisionIn{CurrentFlight: currentFlight, FlightIndex: flightIndex}, &out, _c.inFlow, _c.outFlow)
	return out.Accepted, out.FlightIndexOut, err // No trace
}

// ChooseSeat delegates seat selection for the accepted flight to the ChooseSeatAgent child workflow.
func (_c Executor) ChooseSeat(ctx context.Context, seatPreference string, currentFlight Flight) (seat string, err error) { // MARKER: ChooseSeat
	var out ChooseSeatOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, ChooseSeat.Method, ChooseSeat.Route, ChooseSeatIn{SeatPreference: seatPreference, CurrentFlight: currentFlight}, &out, _c.inFlow, _c.outFlow)
	return out.Seat, err // No trace
}

// ConfirmBooking finalizes the booking of the accepted flight and chosen seat into a confirmation.
func (_c Executor) ConfirmBooking(ctx context.Context, currentFlight Flight, seat string) (confirmation string, airline string, flightNo string, err error) { // MARKER: ConfirmBooking
	var out ConfirmBookingOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, ConfirmBooking.Method, ConfirmBooking.Route, ConfirmBookingIn{CurrentFlight: currentFlight, Seat: seat}, &out, _c.inFlow, _c.outFlow)
	return out.Confirmation, out.Airline, out.FlightNo, err // No trace
}

// NoFlights ends the workflow with a not-booked message when no flight is available or every candidate is
// declined.
func (_c Executor) NoFlights(ctx context.Context) (confirmation string, err error) { // MARKER: NoFlights
	var out NoFlightsOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, NoFlights.Method, NoFlights.Route, NoFlightsIn{}, &out, _c.inFlow, _c.outFlow)
	return out.Confirmation, err // No trace
}

// PickSeat asks the LLM to choose one seat from the available list that best matches the traveler's preference.
func (_c Executor) PickSeat(ctx context.Context, seatPreference string, availableSeats []string) (seat string, err error) { // MARKER: PickSeat
	var out PickSeatOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, PickSeat.Method, PickSeat.Route, PickSeatIn{SeatPreference: seatPreference, AvailableSeats: availableSeats}, &out, _c.inFlow, _c.outFlow)
	return out.Seat, err // No trace
}

// BookFlight is the top-level agentic workflow. It searches the route, then loops proposing one candidate flight
// at a time and parking on a human accept/keep-searching decision via Interrupt. On acceptance it invokes the
// ChooseSeatAgent child workflow as an isolated subgraph to pick a seat, then confirms the booking.
func (_c Executor) BookFlight(ctx context.Context, origin string, destination string, seatPreference string) (confirmation string, airline string, flightNo string, seat string, status string, err error) { // MARKER: BookFlight
	if _c.runner == nil {
		return confirmation, airline, flightNo, seat, "", errors.New("workflow runner not set, use WithWorkflowRunner")
	}
	var out BookFlightOut
	status, err = marshalWorkflow(ctx, _c.runner, _c.flowOptions, BookFlight.URL(), BookFlightIn{Origin: origin, Destination: destination, SeatPreference: seatPreference}, &out)
	return out.Confirmation, out.Airline, out.FlightNo, out.Seat, status, err
}

// BookFlight is the top-level agentic workflow. It searches the route, then loops proposing one candidate flight
// at a time and parking on a human accept/keep-searching decision via Interrupt. On acceptance it invokes the
// ChooseSeatAgent child workflow as an isolated subgraph to pick a seat, then confirms the booking.
func (_sg Subgraph) BookFlight(ctx context.Context, origin string, destination string, seatPreference string) (confirmation string, airline string, flightNo string, seat string, yield bool, err error) { // MARKER: BookFlight
	var out BookFlightOut
	yield, err = marshalSubgraph(_sg.flow, BookFlight.URL(), BookFlightIn{Origin: origin, Destination: destination, SeatPreference: seatPreference}, &out)
	if yield || err != nil {
		return confirmation, airline, flightNo, seat, yield, err
	}
	return out.Confirmation, out.Airline, out.FlightNo, out.Seat, false, nil
}

// ChooseSeatAgent is a child workflow that selects a single seat from a flight's available seats to match a
// natural-language preference. It is invoked as an isolated subgraph by the BookFlight workflow's ChooseSeat task.
func (_c Executor) ChooseSeatAgent(ctx context.Context, seatPreference string, availableSeats []string) (seat string, status string, err error) { // MARKER: ChooseSeatAgent
	if _c.runner == nil {
		return seat, "", errors.New("workflow runner not set, use WithWorkflowRunner")
	}
	var out ChooseSeatAgentOut
	status, err = marshalWorkflow(ctx, _c.runner, _c.flowOptions, ChooseSeatAgent.URL(), ChooseSeatAgentIn{SeatPreference: seatPreference, AvailableSeats: availableSeats}, &out)
	return out.Seat, status, err
}

// ChooseSeatAgent is a child workflow that selects a single seat from a flight's available seats to match a
// natural-language preference. It is invoked as an isolated subgraph by the BookFlight workflow's ChooseSeat task.
func (_sg Subgraph) ChooseSeatAgent(ctx context.Context, seatPreference string, availableSeats []string) (seat string, yield bool, err error) { // MARKER: ChooseSeatAgent
	var out ChooseSeatAgentOut
	yield, err = marshalSubgraph(_sg.flow, ChooseSeatAgent.URL(), ChooseSeatAgentIn{SeatPreference: seatPreference, AvailableSeats: availableSeats}, &out)
	if yield || err != nil {
		return seat, yield, err
	}
	return out.Seat, false, nil
}
