/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package embedder

import (
	"context"
	"net/http"
	"strconv"

	"github.com/microbus-io/dv8"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/cfg"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/exampleservices/embedder/embedderapi"
	"github.com/microbus-io/fabric/exampleservices/embedder/resources"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
)

const (
	Hostname    = embedderapi.Hostname
	Version     = embedderapi.Version
	Description = embedderapi.Description
)

// ToDo is implemented by the service or mock.
// The intermediate delegates handling to this interface.
type ToDo interface {
	OnStartup(ctx context.Context) (err error)
	OnShutdown(ctx context.Context) (err error)
	Embed(ctx context.Context, text string) (vector []float64, err error)          // MARKER: Embed
	Similarity(ctx context.Context, a string, b string) (score float64, err error) // MARKER: Similarity
	Demo(w http.ResponseWriter, r *http.Request) (err error)                       // MARKER: Demo
	DemoInit(w http.ResponseWriter, r *http.Request) (err error)                   // MARKER: DemoInit
	DemoStatus(w http.ResponseWriter, r *http.Request) (err error)                 // MARKER: DemoStatus
}

// NewService creates a new instance of the microservice.
func NewService() *Service {
	svc := &Service{}
	svc.Intermediate = NewIntermediate(svc)
	return svc
}

// Init enables a single-statement pattern for initializing the microservice.
func (svc *Service) Init(initializer func(svc *Service) (err error)) *Service {
	svc.Connector.Init(func(_ *connector.Connector) (err error) {
		return initializer(svc)
	})
	return svc
}

// Intermediate extends and customizes the generic base connector.
type Intermediate struct {
	*connector.Connector
	ToDo
}

// NewIntermediate creates a new instance of the intermediate.
func NewIntermediate(impl ToDo) *Intermediate {
	svc := &Intermediate{
		Connector: connector.New(Hostname),
		ToDo:      impl,
	}
	svc.SetVersion(Version)
	svc.SetDescription(Description)
	svc.SetOnStartup(svc.OnStartup)
	svc.SetOnShutdown(svc.OnShutdown)
	svc.SetResFS(resources.FS)
	svc.SetOnObserveMetrics(svc.doOnObserveMetrics)
	svc.SetOnConfigChanged(svc.doOnConfigChanged)

	svc.Connector.Init(func(_ *connector.Connector) (err error) {
		// Fail startup on a malformed validation directive in an endpoint input type
		return dv8.Compile(
			embedderapi.EmbedIn{},      // MARKER: Embed
			embedderapi.SimilarityIn{}, // MARKER: Similarity
		)
	})

	svc.Subscribe( // MARKER: Embed
		"Embed", svc.doEmbed,
		sub.At(embedderapi.Embed.Method, embedderapi.Embed.Route),
		sub.Description(`Embed returns the sentence-embedding vector for the input text.`),
		sub.Manual(),
		sub.Tag("python"),
		sub.Function(embedderapi.EmbedIn{}, embedderapi.EmbedOut{}),
	)
	svc.Subscribe( // MARKER: Similarity
		"Similarity", svc.doSimilarity,
		sub.At(embedderapi.Similarity.Method, embedderapi.Similarity.Route),
		sub.Description(`Similarity returns the cosine similarity between the embeddings of strings a and b.`),
		sub.Manual(),
		sub.Tag("python"),
		sub.Function(embedderapi.SimilarityIn{}, embedderapi.SimilarityOut{}),
	)
	svc.Subscribe( // MARKER: Demo
		"Demo", svc.Demo,
		sub.At(embedderapi.Demo.Method, embedderapi.Demo.Route),
		sub.Description(`Demo serves the interactive demo page for the embedder.`),
		sub.Web(),
	)
	svc.Subscribe( // MARKER: DemoInit
		"DemoInit", svc.DemoInit,
		sub.At(embedderapi.DemoInit.Method, embedderapi.DemoInit.Route),
		sub.Description(`DemoInit kicks off Python venv allocation in the background. It is idempotent: a second call while
initialization is pending or already ready returns the current status without restarting.`),
		sub.Web(),
	)
	svc.Subscribe( // MARKER: DemoStatus
		"DemoStatus", svc.DemoStatus,
		sub.At(embedderapi.DemoStatus.Method, embedderapi.DemoStatus.Route),
		sub.Description(`DemoStatus is a long-poll endpoint reporting venv initialization status and tailed logs. The client
passes its last-seen ETag via If-None-Match; the server snapshots the current status and logs, hashes
them into an ETag, and:
  - returns 200 with the new ETag and body if the snapshot differs;
  - holds the connection (polling every 500ms) until the snapshot changes;
  - returns 204 No Content when the request is within ~1s of its deadline without any change, so the
    client can immediately re-issue the request with the same ETag.

A fresh client (no If-None-Match) gets the current snapshot back on the first iteration.`),
		sub.Web(),
	)
	svc.DefineConfig( // MARKER: MaxWorkers
		"MaxWorkers",
		cfg.Description(`MaxWorkers caps how many calls into the Python venv may run concurrently.`),
		cfg.DefaultValue(`2`),
		cfg.Validation(`int [1,]`),
	)

	return svc
}

// doOnObserveMetrics is called when metrics are produced.
func (svc *Intermediate) doOnObserveMetrics(ctx context.Context) (err error) {
	return svc.Parallel(ctx)
}

// doOnConfigChanged is called when the config of the microservice changes.
func (svc *Intermediate) doOnConfigChanged(ctx context.Context, changed func(string) bool) (err error) {
	return nil
}

// marshalFunction handles marshaling for functional endpoints.
func marshalFunction(w http.ResponseWriter, r *http.Request, route string, in any, out any, execute func(in any, out any) error) error {
	err := httpx.ReadInputPayload(r, route, in)
	if err != nil {
		return errors.Trace(err)
	}
	// The body is fully decoded into the input, so release it for the duration of the handler
	r.Body = http.NoBody
	err = dv8.Validate(r.Context(), in)
	if err != nil {
		return errors.Trace(err)
	}
	err = execute(in, out)
	if err != nil {
		return err // No trace
	}
	err = httpx.WriteOutputPayload(w, out)
	if err != nil {
		return errors.Trace(err)
	}
	return nil
}

// doEmbed handles marshaling for Embed.
func (svc *Intermediate) doEmbed(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: Embed
	var in embedderapi.EmbedIn
	var out embedderapi.EmbedOut
	err = marshalFunction(w, r, embedderapi.Embed.Route, &in, &out, func(_ any, _ any) error {
		out.Vector, err = svc.Embed(r.Context(), in.Text)
		return err // No trace
	})
	return err // No trace
}

// doSimilarity handles marshaling for Similarity.
func (svc *Intermediate) doSimilarity(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: Similarity
	var in embedderapi.SimilarityIn
	var out embedderapi.SimilarityOut
	err = marshalFunction(w, r, embedderapi.Similarity.Route, &in, &out, func(_ any, _ any) error {
		out.Score, err = svc.Similarity(r.Context(), in.A, in.B)
		return err // No trace
	})
	return err // No trace
}

// MaxWorkers caps how many calls into the Python venv may run concurrently.
func (svc *Intermediate) MaxWorkers() (value int) { // MARKER: MaxWorkers
	_val := svc.Config("MaxWorkers")
	_i, _ := strconv.ParseInt(_val, 10, 64)
	return int(_i)
}

// SetMaxWorkers sets the value of the configuration property.
func (svc *Intermediate) SetMaxWorkers(value int) (err error) { // MARKER: MaxWorkers
	return svc.SetConfig("MaxWorkers", strconv.Itoa(value))
}
