/*
Copyright (c) 2023-2024 Microbus LLC and various contributors

This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
Neither may be used, copied or distributed without the express written consent of Microbus LLC.
*/

// Code generated by Microbus. DO NOT EDIT.

package configurator

const Version = 130
const SourceCodeSHA256 = "60049a02bb856b0f7c70211e6843e33ba340285ac50cb8d3ab21e02e32a58e80"
const Timestamp = "2024-05-20T14:36:53.362383Z"

/* {
	"ver": 130,
	"sha256": "60049a02bb856b0f7c70211e6843e33ba340285ac50cb8d3ab21e02e32a58e80",
	"ts": "2024-05-20T14:36:53.362383Z"
} */
