/*
Copyright 2023 Microbus Open Source Foundation and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Package rand is a utility that combines crypto.rand and math.rand for more secure random number generation with
reduced performance impact.
The package keeps a pool of math generators, making it unlikely that two consecutive random numbers are
generated by the same math generator.
It also reseeds the math generators occassionally using a seed generated by a crypto generator.
*/
package rand
