{
 "title": "System Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Req/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(microbus_response_duration_seconds_count{port!=\"888\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "piechart",
   "description": "Status codes returned by the server",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(error, code) (rate(microbus_response_duration_seconds_count[$__rate_interval])) != 0",
     "legendFormat": "{{error}} {{code}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(microbus_uptime_duration_seconds_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(microbus_response_duration_seconds_count{port!=\"888\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(microbus_uptime_duration_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Error Rate",
   "type": "timeseries",
   "description": "Non-200 status codes seen by the server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(microbus_response_duration_seconds_count{port!=\"888\", code!=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Processing Duration 100%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, service) (rate(microbus_response_duration_seconds_bucket{port!=\"888\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "timeseries",
   "description": "Non-200 error codes seen by the client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(error, code, host, port, path) (rate(microbus_request_count_total{port!=\"888\", code!=\"200\"}[$__rate_interval])) != 0",
     "legendFormat": "{{error}} {{code}} {{host}}:{{port}}{{path}}"
    }
   ]
  },
  {
   "title": "Response Size 100%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, service) (rate(microbus_response_size_bytes_bucket{port!=\"888\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(microbus_log_messages_total{severity=\"ERROR\"}[$__rate_interval])) != 0",
     "legendFormat": "{{service}} {{message}}"
    }
   ]
  },
  {
   "title": "Ack Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(microbus_ack_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(microbus_ack_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Log Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(severity, message) (rate(microbus_log_messages_total{severity!=\"DEBUG\"}[$__rate_interval])) != 0",
     "legendFormat": "{{severity}} {{message}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(service, ver) (microbus_uptime_duration_seconds_total)",
     "legendFormat": "{{service}} v{{ver}}"
    }
   ]
  },
  {
   "title": "Callback Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(microbus_callback_duration_seconds_count{error=\"true\"}[$__rate_interval])) != 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Callback Processing Duration 100%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, service) (rate(microbus_callback_duration_seconds_bucket[$__rate_interval]))) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributed Cache Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(service) (microbus_cache_weight_total) !=0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}