// Code generated by cmd/genservice. DO NOT EDIT.

package foreman

import (
	"context"
	"net/http"

	"github.com/microbus-io/dwarf/workflow"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/coreservices/foreman/foremanapi"
)

// Mock is a mockable version of the microservice, allowing functions, event sinks and web handlers to be mocked.
type Mock struct {
	*Intermediate
	mockCreate         func(ctx context.Context, workflowURL string, initialState any, opts *workflow.FlowOptions) (flowKey string, err error)                // MARKER: Create
	mockSnapshot       func(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error)                                                   // MARKER: Snapshot
	mockFingerprint    func(ctx context.Context, flowKey string) (fingerprint string, status string, err error)                                               // MARKER: Fingerprint
	mockResume         func(ctx context.Context, flowKey string, resumeData any) (err error)                                                                  // MARKER: Resume
	mockCancel         func(ctx context.Context, flowKey string, reason string) (err error)                                                                   // MARKER: Cancel
	mockFork           func(ctx context.Context, stepKey string, stateOverrides any) (newFlowKey string, err error)                                           // MARKER: Fork
	mockHistory        func(ctx context.Context, flowKey string) (steps []foremanapi.FlowStep, err error)                                                     // MARKER: History
	mockStep           func(ctx context.Context, stepKey string) (step *foremanapi.FlowStep, err error)                                                       // MARKER: Step
	mockList           func(ctx context.Context, query foremanapi.Query) (flows []foremanapi.FlowSummary, nextCursor string, err error)                       // MARKER: List
	mockDelete         func(ctx context.Context, flowKey string) (err error)                                                                                  // MARKER: Delete
	mockPurge          func(ctx context.Context, query foremanapi.Query) (deleted int, err error)                                                             // MARKER: Purge
	mockShardInfo      func(ctx context.Context) (shards []foremanapi.ShardSummary, err error)                                                                // MARKER: ShardInfo
	mockAwait          func(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error)                                                   // MARKER: Await
	mockPoll           func(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error)                                                   // MARKER: Poll
	mockRun            func(ctx context.Context, workflowURL string, initialState any, opts *workflow.FlowOptions) (outcome *workflow.FlowOutcome, err error) // MARKER: Run
	mockContinue       func(ctx context.Context, threadKey string, additionalState any) (newFlowKey string, err error)                                        // MARKER: Continue
	mockHistoryMermaid func(w http.ResponseWriter, r *http.Request) (err error)                                                                               // MARKER: HistoryMermaid
}

// NewMock creates a new mockable version of the microservice.
func NewMock() *Mock {
	svc := &Mock{}
	svc.Intermediate = NewIntermediate(svc)
	svc.SetVersion(7357) // Stands for TEST
	return svc
}

// OnStartup is called when the microservice is started up.
func (svc *Mock) OnStartup(ctx context.Context) (err error) {
	if svc.Deployment() != connector.LOCAL && svc.Deployment() != connector.TESTING {
		return errors.New("mocking disallowed in %s deployment", svc.Deployment())
	}
	return nil
}

// OnShutdown is called when the microservice is shut down.
func (svc *Mock) OnShutdown(ctx context.Context) (err error) {
	return nil
}

// MockCreate sets up a mock handler for Create.
func (svc *Mock) MockCreate(handler func(ctx context.Context, workflowURL string, initialState any, opts *workflow.FlowOptions) (flowKey string, err error)) *Mock { // MARKER: Create
	svc.mockCreate = handler
	return svc
}

// Create executes the mock handler.
func (svc *Mock) Create(ctx context.Context, workflowURL string, initialState any, opts *workflow.FlowOptions) (flowKey string, err error) { // MARKER: Create
	if svc.mockCreate != nil {
		flowKey, err = svc.mockCreate(ctx, workflowURL, initialState, opts)
	}
	return flowKey, errors.Trace(err)
}

// MockSnapshot sets up a mock handler for Snapshot.
func (svc *Mock) MockSnapshot(handler func(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error)) *Mock { // MARKER: Snapshot
	svc.mockSnapshot = handler
	return svc
}

// Snapshot executes the mock handler.
func (svc *Mock) Snapshot(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error) { // MARKER: Snapshot
	if svc.mockSnapshot != nil {
		outcome, err = svc.mockSnapshot(ctx, flowKey)
	}
	return outcome, errors.Trace(err)
}

// MockFingerprint sets up a mock handler for Fingerprint.
func (svc *Mock) MockFingerprint(handler func(ctx context.Context, flowKey string) (fingerprint string, status string, err error)) *Mock { // MARKER: Fingerprint
	svc.mockFingerprint = handler
	return svc
}

// Fingerprint executes the mock handler.
func (svc *Mock) Fingerprint(ctx context.Context, flowKey string) (fingerprint string, status string, err error) { // MARKER: Fingerprint
	if svc.mockFingerprint != nil {
		fingerprint, status, err = svc.mockFingerprint(ctx, flowKey)
	}
	return fingerprint, status, errors.Trace(err)
}

// MockResume sets up a mock handler for Resume.
func (svc *Mock) MockResume(handler func(ctx context.Context, flowKey string, resumeData any) (err error)) *Mock { // MARKER: Resume
	svc.mockResume = handler
	return svc
}

// Resume executes the mock handler.
func (svc *Mock) Resume(ctx context.Context, flowKey string, resumeData any) (err error) { // MARKER: Resume
	if svc.mockResume != nil {
		err = svc.mockResume(ctx, flowKey, resumeData)
	}
	return errors.Trace(err)
}

// MockCancel sets up a mock handler for Cancel.
func (svc *Mock) MockCancel(handler func(ctx context.Context, flowKey string, reason string) (err error)) *Mock { // MARKER: Cancel
	svc.mockCancel = handler
	return svc
}

// Cancel executes the mock handler.
func (svc *Mock) Cancel(ctx context.Context, flowKey string, reason string) (err error) { // MARKER: Cancel
	if svc.mockCancel != nil {
		err = svc.mockCancel(ctx, flowKey, reason)
	}
	return errors.Trace(err)
}

// MockFork sets up a mock handler for Fork.
func (svc *Mock) MockFork(handler func(ctx context.Context, stepKey string, stateOverrides any) (newFlowKey string, err error)) *Mock { // MARKER: Fork
	svc.mockFork = handler
	return svc
}

// Fork executes the mock handler.
func (svc *Mock) Fork(ctx context.Context, stepKey string, stateOverrides any) (newFlowKey string, err error) { // MARKER: Fork
	if svc.mockFork != nil {
		newFlowKey, err = svc.mockFork(ctx, stepKey, stateOverrides)
	}
	return newFlowKey, errors.Trace(err)
}

// MockHistory sets up a mock handler for History.
func (svc *Mock) MockHistory(handler func(ctx context.Context, flowKey string) (steps []foremanapi.FlowStep, err error)) *Mock { // MARKER: History
	svc.mockHistory = handler
	return svc
}

// History executes the mock handler.
func (svc *Mock) History(ctx context.Context, flowKey string) (steps []foremanapi.FlowStep, err error) { // MARKER: History
	if svc.mockHistory != nil {
		steps, err = svc.mockHistory(ctx, flowKey)
	}
	return steps, errors.Trace(err)
}

// MockStep sets up a mock handler for Step.
func (svc *Mock) MockStep(handler func(ctx context.Context, stepKey string) (step *foremanapi.FlowStep, err error)) *Mock { // MARKER: Step
	svc.mockStep = handler
	return svc
}

// Step executes the mock handler.
func (svc *Mock) Step(ctx context.Context, stepKey string) (step *foremanapi.FlowStep, err error) { // MARKER: Step
	if svc.mockStep != nil {
		step, err = svc.mockStep(ctx, stepKey)
	}
	return step, errors.Trace(err)
}

// MockList sets up a mock handler for List.
func (svc *Mock) MockList(handler func(ctx context.Context, query foremanapi.Query) (flows []foremanapi.FlowSummary, nextCursor string, err error)) *Mock { // MARKER: List
	svc.mockList = handler
	return svc
}

// List executes the mock handler.
func (svc *Mock) List(ctx context.Context, query foremanapi.Query) (flows []foremanapi.FlowSummary, nextCursor string, err error) { // MARKER: List
	if svc.mockList != nil {
		flows, nextCursor, err = svc.mockList(ctx, query)
	}
	return flows, nextCursor, errors.Trace(err)
}

// MockDelete sets up a mock handler for Delete.
func (svc *Mock) MockDelete(handler func(ctx context.Context, flowKey string) (err error)) *Mock { // MARKER: Delete
	svc.mockDelete = handler
	return svc
}

// Delete executes the mock handler.
func (svc *Mock) Delete(ctx context.Context, flowKey string) (err error) { // MARKER: Delete
	if svc.mockDelete != nil {
		err = svc.mockDelete(ctx, flowKey)
	}
	return errors.Trace(err)
}

// MockPurge sets up a mock handler for Purge.
func (svc *Mock) MockPurge(handler func(ctx context.Context, query foremanapi.Query) (deleted int, err error)) *Mock { // MARKER: Purge
	svc.mockPurge = handler
	return svc
}

// Purge executes the mock handler.
func (svc *Mock) Purge(ctx context.Context, query foremanapi.Query) (deleted int, err error) { // MARKER: Purge
	if svc.mockPurge != nil {
		deleted, err = svc.mockPurge(ctx, query)
	}
	return deleted, errors.Trace(err)
}

// MockShardInfo sets up a mock handler for ShardInfo.
func (svc *Mock) MockShardInfo(handler func(ctx context.Context) (shards []foremanapi.ShardSummary, err error)) *Mock { // MARKER: ShardInfo
	svc.mockShardInfo = handler
	return svc
}

// ShardInfo executes the mock handler.
func (svc *Mock) ShardInfo(ctx context.Context) (shards []foremanapi.ShardSummary, err error) { // MARKER: ShardInfo
	if svc.mockShardInfo != nil {
		shards, err = svc.mockShardInfo(ctx)
	}
	return shards, errors.Trace(err)
}

// MockAwait sets up a mock handler for Await.
func (svc *Mock) MockAwait(handler func(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error)) *Mock { // MARKER: Await
	svc.mockAwait = handler
	return svc
}

// Await executes the mock handler.
func (svc *Mock) Await(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error) { // MARKER: Await
	if svc.mockAwait != nil {
		outcome, err = svc.mockAwait(ctx, flowKey)
	}
	return outcome, errors.Trace(err)
}

// MockPoll sets up a mock handler for Poll.
func (svc *Mock) MockPoll(handler func(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error)) *Mock { // MARKER: Poll
	svc.mockPoll = handler
	return svc
}

// Poll executes the mock handler.
func (svc *Mock) Poll(ctx context.Context, flowKey string) (outcome *workflow.FlowOutcome, err error) { // MARKER: Poll
	if svc.mockPoll != nil {
		outcome, err = svc.mockPoll(ctx, flowKey)
	}
	return outcome, errors.Trace(err)
}

// MockRun sets up a mock handler for Run.
func (svc *Mock) MockRun(handler func(ctx context.Context, workflowURL string, initialState any, opts *workflow.FlowOptions) (outcome *workflow.FlowOutcome, err error)) *Mock { // MARKER: Run
	svc.mockRun = handler
	return svc
}

// Run executes the mock handler.
func (svc *Mock) Run(ctx context.Context, workflowURL string, initialState any, opts *workflow.FlowOptions) (outcome *workflow.FlowOutcome, err error) { // MARKER: Run
	if svc.mockRun != nil {
		outcome, err = svc.mockRun(ctx, workflowURL, initialState, opts)
	}
	return outcome, errors.Trace(err)
}

// MockContinue sets up a mock handler for Continue.
func (svc *Mock) MockContinue(handler func(ctx context.Context, threadKey string, additionalState any) (newFlowKey string, err error)) *Mock { // MARKER: Continue
	svc.mockContinue = handler
	return svc
}

// Continue executes the mock handler.
func (svc *Mock) Continue(ctx context.Context, threadKey string, additionalState any) (newFlowKey string, err error) { // MARKER: Continue
	if svc.mockContinue != nil {
		newFlowKey, err = svc.mockContinue(ctx, threadKey, additionalState)
	}
	return newFlowKey, errors.Trace(err)
}

// MockHistoryMermaid sets up a mock handler for HistoryMermaid.
func (svc *Mock) MockHistoryMermaid(handler func(w http.ResponseWriter, r *http.Request) (err error)) *Mock { // MARKER: HistoryMermaid
	svc.mockHistoryMermaid = handler
	return svc
}

// HistoryMermaid executes the mock handler.
func (svc *Mock) HistoryMermaid(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: HistoryMermaid
	if svc.mockHistoryMermaid != nil {
		err = svc.mockHistoryMermaid(w, r)
	}
	return errors.Trace(err)
}
