// Code generated by cmd/genservice. DO NOT EDIT.

package petstore

import (
	"context"
	"net/http"

	"github.com/microbus-io/dv8"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/cfg"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/exampleservices/petstore/petstoreapi"
	"github.com/microbus-io/fabric/exampleservices/petstore/resources"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
)

const (
	Hostname    = petstoreapi.Hostname
	Version     = petstoreapi.Version
	Description = petstoreapi.Description
)

// ToDo is implemented by the service or mock.
// The intermediate delegates handling to this interface.
type ToDo interface {
	OnStartup(ctx context.Context) (err error)
	OnShutdown(ctx context.Context) (err error)
	AddPet(ctx context.Context, httpRequestBody *petstoreapi.Pet) (httpResponseBody *petstoreapi.Pet, httpStatusCode int, err error) // MARKER: AddPet
	GetPetById(ctx context.Context, petId int64) (httpResponseBody *petstoreapi.Pet, httpStatusCode int, err error)                  // MARKER: GetPetById
	UploadFile(w http.ResponseWriter, r *http.Request) (err error)                                                                   // MARKER: UploadFile
}

// NewService creates a new instance of the microservice.
func NewService() *Service {
	svc := &Service{}
	svc.Intermediate = NewIntermediate(svc)
	return svc
}

// Init enables a single-statement pattern for initializing the microservice.
func (svc *Service) Init(initializer func(svc *Service) (err error)) *Service {
	svc.Connector.Init(func(_ *connector.Connector) (err error) {
		return initializer(svc)
	})
	return svc
}

// Intermediate extends and customizes the generic base connector.
type Intermediate struct {
	*connector.Connector
	ToDo
}

// NewIntermediate creates a new instance of the intermediate.
func NewIntermediate(impl ToDo) *Intermediate {
	svc := &Intermediate{
		Connector: connector.New(Hostname),
		ToDo:      impl,
	}
	svc.SetVersion(Version)
	svc.SetDescription(Description)
	svc.SetOnStartup(svc.OnStartup)
	svc.SetOnShutdown(svc.OnShutdown)
	svc.SetResFS(resources.FS)
	svc.SetOnObserveMetrics(svc.doOnObserveMetrics)
	svc.SetOnConfigChanged(svc.doOnConfigChanged)

	svc.Connector.Init(func(_ *connector.Connector) (err error) {
		// Fail startup on a malformed validation directive in an endpoint input type
		return dv8.Compile(
			petstoreapi.AddPetIn{},     // MARKER: AddPet
			petstoreapi.GetPetByIdIn{}, // MARKER: GetPetById
		)
	})

	svc.Subscribe( // MARKER: AddPet
		"AddPet", svc.doAddPet,
		sub.At(petstoreapi.AddPet.Method, petstoreapi.AddPet.Route),
		sub.Description(`AddPet adds a new pet to the store.`),
		sub.Function(petstoreapi.AddPetIn{}, petstoreapi.AddPetOut{}),
	)
	svc.Subscribe( // MARKER: GetPetById
		"GetPetById", svc.doGetPetById,
		sub.At(petstoreapi.GetPetById.Method, petstoreapi.GetPetById.Route),
		sub.Description(`GetPetById returns a single pet.`),
		sub.Function(petstoreapi.GetPetByIdIn{}, petstoreapi.GetPetByIdOut{}),
	)
	svc.Subscribe( // MARKER: UploadFile
		"UploadFile", svc.UploadFile,
		sub.At(petstoreapi.UploadFile.Method, petstoreapi.UploadFile.Route),
		sub.Description(`UploadFile uploads an image of the pet.`),
		sub.Web(),
	)
	svc.DefineConfig( // MARKER: RemoteBaseURL
		"RemoteBaseURL",
		cfg.Description(`RemoteBaseURL is the base URL of the remote Swagger Petstore API.`),
		cfg.DefaultValue(`https://petstore3.swagger.io/api/v3`),
		cfg.Validation(`url`),
	)
	svc.DefineConfig( // MARKER: BearerToken
		"BearerToken",
		cfg.Description(`BearerToken is the OAuth2 bearer token presented to the remote Swagger Petstore API.`),
		cfg.Secret(),
	)

	return svc
}

// doOnObserveMetrics is called when metrics are produced.
func (svc *Intermediate) doOnObserveMetrics(ctx context.Context) (err error) {
	return svc.Parallel(ctx)
}

// doOnConfigChanged is called when the config of the microservice changes.
func (svc *Intermediate) doOnConfigChanged(ctx context.Context, changed func(string) bool) (err error) {
	return nil
}

// marshalFunction handles marshaling for functional endpoints.
func marshalFunction(w http.ResponseWriter, r *http.Request, route string, in any, out any, execute func(in any, out any) error) error {
	err := httpx.ReadInputPayload(r, route, in)
	if err != nil {
		return errors.Trace(err)
	}
	// The body is fully decoded into the input, so release it for the duration of the handler
	r.Body = http.NoBody
	err = dv8.Validate(r.Context(), in)
	if err != nil {
		return errors.Trace(err)
	}
	err = execute(in, out)
	if err != nil {
		return err // No trace
	}
	err = httpx.WriteOutputPayload(w, out)
	if err != nil {
		return errors.Trace(err)
	}
	return nil
}

// doAddPet handles marshaling for AddPet.
func (svc *Intermediate) doAddPet(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: AddPet
	var in petstoreapi.AddPetIn
	var out petstoreapi.AddPetOut
	err = marshalFunction(w, r, petstoreapi.AddPet.Route, &in, &out, func(_ any, _ any) error {
		out.HTTPResponseBody, out.HTTPStatusCode, err = svc.AddPet(r.Context(), in.HTTPRequestBody)
		return err // No trace
	})
	return err // No trace
}

// doGetPetById handles marshaling for GetPetById.
func (svc *Intermediate) doGetPetById(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: GetPetById
	var in petstoreapi.GetPetByIdIn
	var out petstoreapi.GetPetByIdOut
	err = marshalFunction(w, r, petstoreapi.GetPetById.Route, &in, &out, func(_ any, _ any) error {
		out.HTTPResponseBody, out.HTTPStatusCode, err = svc.GetPetById(r.Context(), in.PetId)
		return err // No trace
	})
	return err // No trace
}

// RemoteBaseURL is the base URL of the remote Swagger Petstore API.
func (svc *Intermediate) RemoteBaseURL() (value string) { // MARKER: RemoteBaseURL
	return svc.Config("RemoteBaseURL")
}

// SetRemoteBaseURL sets the value of the configuration property.
func (svc *Intermediate) SetRemoteBaseURL(value string) (err error) { // MARKER: RemoteBaseURL
	return svc.SetConfig("RemoteBaseURL", value)
}

// BearerToken is the OAuth2 bearer token presented to the remote Swagger Petstore API.
func (svc *Intermediate) BearerToken() (value string) { // MARKER: BearerToken
	return svc.Config("BearerToken")
}

// SetBearerToken sets the value of the configuration property.
func (svc *Intermediate) SetBearerToken(value string) (err error) { // MARKER: BearerToken
	return svc.SetConfig("BearerToken", value)
}
