/*
Copyright (c) 2023-2024 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Microbus. DO NOT EDIT.

package resources

import "embed"

//go:embed *
var FS embed.FS

/*
Files placed in the resources directory are bundled with the executable and are accessible via svc.ResFS or
any of the convenience methods svc.ReadResFile, svc.ReadResTextFile, svc.ExecuteResTemplate, svc.ServeResFile, etc.

A file named strings.yaml can be used to store internationalized strings that can be loaded via svc.LoadResString
to best match the locale in the context. The YAML is expected to be in the following format:

stringKey:
  default: Localized
  en: Localized
  en-GB: Localised
  fr: Localisée

If a default is not provided, English (en) is used as the fallback language.
String keys and locale names are case-sensitive.
*/
