/*
Copyright (c) 2023-2024 Microbus LLC and various contributors

This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
Neither may be used, copied or distributed without the express written consent of Microbus LLC.
*/

// Code generated by Microbus. DO NOT EDIT.

package directory

const Version = 135
const SourceCodeSHA256 = "b3561c45b764e9bc7b2562429b06a7c9803d0bb451656b6b05ce8e64b9f76bd5"
const Timestamp = "2024-06-02T02:27:17.838579Z"

/* {
	"ver": 135,
	"sha256": "b3561c45b764e9bc7b2562429b06a7c9803d0bb451656b6b05ce8e64b9f76bd5",
	"ts": "2024-06-02T02:27:17.838579Z"
} */
