// Code generated by Microbus. DO NOT EDIT.

package calculator

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"testing"
	"time"

	"github.com/microbus-io/fabric/application"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/services/configurator"
	"github.com/microbus-io/fabric/utils"

	"github.com/stretchr/testify/assert"

	"github.com/microbus-io/fabric/examples/calculator/calculatorapi"
)

var (
	_ bytes.Buffer
	_ context.Context
	_ fmt.Stringer
	_ io.Reader
	_ *http.Request
	_ os.File
	_ time.Time
	_ *httpx.BodyReader
	_ pub.Option
	_ utils.InfiniteChan[int]
	_ assert.TestingT
	_ *calculatorapi.Client
)

var (
	// App manages the lifecycle of the microservices used in the test.
	App *application.Application
	// Configurator is the configurator system microservice.
	Configurator connector.Service
	// Svc is the calculator.example microservice being tested.
	Svc *Service
)

func TestMain(m *testing.M) {
	var code int

	// Initialize the application
	err := func() error {
		App = application.NewTesting()
		Configurator = configurator.NewService()
		Svc = NewService().(*Service)
		err := Initialize()
		if err != nil {
			return err
		}
		err = App.Startup()
		if err != nil {
			return err
		}
		return nil
	}()
	if err != nil {
		fmt.Fprintf(os.Stderr, "--- FAIL: %+v\n", err)
		code = 19
	}

	// Run the tests
	if err == nil {
		code = m.Run()
	}

	// Terminate the app
	err = func() error {
		var lastErr error
		err = Terminate()
		if err != nil {
			lastErr = err
		}
		err := App.Shutdown()
		if err != nil {
			lastErr = err
		}
		return lastErr
	}()
	if err != nil {
		fmt.Fprintf(os.Stderr, "--- FAIL: %+v\n", err)
	}

	os.Exit(code)
}

// Context creates a new context for a test.
func Context() context.Context {
	return context.Background()
}

type WebOption func(req *pub.Request) error

// GET sets the method of the request.
func GET() WebOption {
	return WebOption(pub.Method("GET"))
}

// DELETE sets the method of the request.
func DELETE() WebOption {
	return WebOption(pub.Method("DELETE"))
}

// HEAD sets the method of the request.
func HEAD() WebOption {
	return WebOption(pub.Method("HEAD"))
}

// POST sets the method and body of the request.
func POST(body any) WebOption {
	return func(req *pub.Request) error {
		pub.Method("POST")(req)
		return pub.Body(body)(req)
	}
}

// PUT sets the method and body of the request.
func PUT(body any) WebOption {
	return func(req *pub.Request) error {
		pub.Method("PUT")(req)
		return pub.Body(body)(req)
	}
}

// PATCH sets the method and body of the request.
func PATCH(body any) WebOption {
	return func(req *pub.Request) error {
		pub.Method("PATCH")(req)
		return pub.Body(body)(req)
	}
}

// Method sets the method of the request.
func Method(method string) WebOption {
	return WebOption(pub.Method(method))
}

// Header add the header to the request.
// The same header may have multiple values.
func Header(name string, value string) WebOption {
	return WebOption(pub.Header(name, value))
}

// QueryArg adds the query argument to the request.
// The same argument may have multiple values.
func QueryArg(name string, value any) WebOption {
	return WebOption(pub.QueryArg(name, value))
}

// Query adds the escaped query arguments to the request.
// The same argument may have multiple values.
func Query(escapedQueryArgs string) WebOption {
	return WebOption(pub.Query(escapedQueryArgs))
}

// Body sets the body of the request.
// Arguments of type io.Reader, []byte and string are serialized in binary form.
// url.Values is serialized as form data.
// All other types are serialized as JSON.
func Body(body any) WebOption {
	return WebOption(pub.Body(body))
}

// ContentType sets the Content-Type header.
func ContentType(contentType string) WebOption {
	return WebOption(pub.ContentType(contentType))
}

// ArithmeticTestCase assists in asserting against the results of executing Arithmetic.
type ArithmeticTestCase struct {
	xEcho int
	opEcho string
	yEcho int
	result int
	err error

	Expect  func(t *testing.T, xEcho int, opEcho string, yEcho int, result int) *ArithmeticTestCase
	Error   func(t *testing.T, errContains string) *ArithmeticTestCase
	NoError func(t *testing.T) *ArithmeticTestCase
}

// Get returns the result of executing Arithmetic.
func (tc *ArithmeticTestCase) Get() (xEcho int, opEcho string, yEcho int, result int, err error) {
	return tc.xEcho, tc.opEcho, tc.yEcho, tc.result, tc.err
}

// Arithmetic executes the function and returns a corresponding test case.
func Arithmetic(ctx context.Context, x int, op string, y int) *ArithmeticTestCase {
	tc := &ArithmeticTestCase{}
	tc.err = utils.CatchPanic(func() error {
		tc.xEcho, tc.opEcho, tc.yEcho, tc.result, tc.err = Svc.Arithmetic(ctx, x, op, y)
		return tc.err
	})
	tc.Expect = func(t *testing.T, xEcho int, opEcho string, yEcho int, result int) *ArithmeticTestCase {
		if assert.NoError(t, tc.err) {
			assert.Equal(t, xEcho, tc.xEcho)
			assert.Equal(t, opEcho, tc.opEcho)
			assert.Equal(t, yEcho, tc.yEcho)
			assert.Equal(t, result, tc.result)
		}
		return tc
	}
	tc.Error = func(t *testing.T, errContains string) *ArithmeticTestCase {
		if assert.Error(t, tc.err) {
			assert.Contains(t, tc.err.Error(), errContains)
		}
		return tc
	}
	tc.NoError = func(t *testing.T) *ArithmeticTestCase {
		assert.NoError(t, tc.err)
		return tc
	}
	return tc
}

// SquareTestCase assists in asserting against the results of executing Square.
type SquareTestCase struct {
	xEcho int
	result int
	err error

	Expect  func(t *testing.T, xEcho int, result int) *SquareTestCase
	Error   func(t *testing.T, errContains string) *SquareTestCase
	NoError func(t *testing.T) *SquareTestCase
}

// Get returns the result of executing Square.
func (tc *SquareTestCase) Get() (xEcho int, result int, err error) {
	return tc.xEcho, tc.result, tc.err
}

// Square executes the function and returns a corresponding test case.
func Square(ctx context.Context, x int) *SquareTestCase {
	tc := &SquareTestCase{}
	tc.err = utils.CatchPanic(func() error {
		tc.xEcho, tc.result, tc.err = Svc.Square(ctx, x)
		return tc.err
	})
	tc.Expect = func(t *testing.T, xEcho int, result int) *SquareTestCase {
		if assert.NoError(t, tc.err) {
			assert.Equal(t, xEcho, tc.xEcho)
			assert.Equal(t, result, tc.result)
		}
		return tc
	}
	tc.Error = func(t *testing.T, errContains string) *SquareTestCase {
		if assert.Error(t, tc.err) {
			assert.Contains(t, tc.err.Error(), errContains)
		}
		return tc
	}
	tc.NoError = func(t *testing.T) *SquareTestCase {
		assert.NoError(t, tc.err)
		return tc
	}
	return tc
}

// DistanceTestCase assists in asserting against the results of executing Distance.
type DistanceTestCase struct {
	d float64
	err error

	Expect  func(t *testing.T, d float64) *DistanceTestCase
	Error   func(t *testing.T, errContains string) *DistanceTestCase
	NoError func(t *testing.T) *DistanceTestCase
}

// Get returns the result of executing Distance.
func (tc *DistanceTestCase) Get() (d float64, err error) {
	return tc.d, tc.err
}

// Distance executes the function and returns a corresponding test case.
func Distance(ctx context.Context, p1 calculatorapi.Point, p2 calculatorapi.Point) *DistanceTestCase {
	tc := &DistanceTestCase{}
	tc.err = utils.CatchPanic(func() error {
		tc.d, tc.err = Svc.Distance(ctx, p1, p2)
		return tc.err
	})
	tc.Expect = func(t *testing.T, d float64) *DistanceTestCase {
		if assert.NoError(t, tc.err) {
			assert.Equal(t, d, tc.d)
		}
		return tc
	}
	tc.Error = func(t *testing.T, errContains string) *DistanceTestCase {
		if assert.Error(t, tc.err) {
			assert.Contains(t, tc.err.Error(), errContains)
		}
		return tc
	}
	tc.NoError = func(t *testing.T) *DistanceTestCase {
		assert.NoError(t, tc.err)
		return tc
	}
	return tc
}
