/*
Copyright (c) 2023-2024 Microbus LLC and various contributors

This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
Neither may be used, copied or distributed without the express written consent of Microbus LLC.
*/

// Code generated by Microbus. DO NOT EDIT.

package eventsink

const Version = 109
const SourceCodeSHA256 = "f1af851732b2006c2ca807c3f26447161259155496f24ea1c29ca67adce778e3"
const Timestamp = "2024-04-22T19:19:30.85179Z"

/* {
	"ver": 109,
	"sha256": "f1af851732b2006c2ca807c3f26447161259155496f24ea1c29ca67adce778e3",
	"ts": "2024-04-22T19:19:30.85179Z"
} */
