// Code generated by Microbus. DO NOT EDIT.

package eventsink

const Version = 71
const SourceCodeSHA256 = "5505c008c012a738ca380bdf6571f766e5b082d4045167a4165572fd7b17938a"
const Timestamp = "2023-01-15T03:28:41.036294Z"

/* {
	"ver": 71,
	"sha256": "5505c008c012a738ca380bdf6571f766e5b082d4045167a4165572fd7b17938a",
	"ts": "2023-01-15T03:28:41.036294Z"
} */
