// Code generated by Microbus. DO NOT EDIT.

package httpingress

const Version = 53
const SourceCodeSHA256 = "e6bd80d995775e2244712eb04e219cc8c9dd1435ec3cff983a079f0118327401"
const Timestamp = "2023-01-13T20:40:13.025782Z"

/* {
	"ver": 53,
	"sha256": "e6bd80d995775e2244712eb04e219cc8c9dd1435ec3cff983a079f0118327401",
	"ts": "2023-01-13T20:40:13.025782Z"
} */
