global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    
    metrics_path: '/metrics.sys/collect'

    static_configs:
      - targets: ["host.docker.internal:8080"]