{
 "title": "Microservice Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(microbus_uptime_duration_seconds_total, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Req/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(microbus_response_duration_seconds_count{port!=\"888\", service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "description": "Status codes returned by the server",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(error, code) (rate(microbus_response_duration_seconds_count{service=\"$service\"}[$__rate_interval])) !=0",
     "legendFormat": "{{error}} {{code}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(microbus_uptime_duration_seconds_total{service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(port, method, handler) (rate(microbus_response_duration_seconds_count{port!=\"888\", service=\"$service\"}[$__rate_interval]))",
     "legendFormat": ":{{port}} {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(microbus_uptime_duration_seconds_total{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Error Rate",
   "type": "timeseries",
   "description": "Non-200 status codes seen by the server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(microbus_response_duration_seconds_count{port!=\"888\", code!=\"200\", service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Processing Duration 100%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, port, method, handler) (rate(microbus_response_duration_seconds_bucket{port!=\"888\", service=\"$service\"}[$__rate_interval])))",
     "legendFormat": ":{{port}} {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "timeseries",
   "description": "Non-200 error codes seen by the client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(error, code, host, port, path) (rate(microbus_request_count_total{port!=\"888\", code!=\"200\", service=\"$service\"}[$__rate_interval])) != 0",
     "legendFormat": "{{error}} {{code}} {{host}}:{{port}}{{path}}"
    }
   ]
  },
  {
   "title": "Response Size 100%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, port, method, handler) (rate(microbus_response_size_bytes_bucket{port!=\"888\", service=\"$service\"}[$__rate_interval])))",
     "legendFormat": ":{{port}} {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Log Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(severity, message) (rate(microbus_log_messages_total{service=\"$service\"}[$__rate_interval])) != 0",
     "legendFormat": "{{severity}} {{message}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(ver, id) (microbus_uptime_duration_seconds_total{service=\"$service\"})",
     "legendFormat": "v{{ver}} {{id}}"
    }
   ]
  },
  {
   "title": "Callback Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(microbus_callback_duration_seconds_count{error=\"ERROR\", service=\"$service\"}[$__rate_interval])) != 0",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Callback Processing Duration 100%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, handler) (rate(microbus_callback_duration_seconds_bucket{service=\"$service\"}[$__rate_interval]))) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributed Cache Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id) (microbus_cache_weight_total{service=\"$service\"}) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributed Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(microbus_cache_hits_total{service=\"$service\"}[$__rate_interval])) /\n(\n    sum(rate(microbus_cache_hits_total{service=\"$service\"}[$__rate_interval])) +\n    sum(rate(microbus_cache_misses_total{service=\"$service\"}[$__rate_interval]))\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}