---
# General
#
# host - The host name of the microservice
# description - A human-friendly description of the microservice
general:
  host: configurator.sys
  description: The Configurator is a system microservice that centralizes the dissemination of configuration values to other microservices.

# Config properties
#
# signature - Func() (val Type)
# description - Documentation
# default - A default value (defaults to empty)
# validation - A validation pattern
#   str ^[a-zA-Z0-9]+$
#   bool
#   int [0,60]
#   float [0.0,1.0)
#   dur (0s,24h]
#   set Red|Green|Blue
#   url
#   email
#   json
# callback - "true" to handle the change event (defaults to "false")
# secret - "true" to indicate a secret (defaults to "false")
configs:
  # - signature:
  #   description:
  #   default:
  #   validation:

# Functions
#
# signature - Func(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path
#   /directory/
#   :123/path
#   :123/... - Ellipsis denotes the function name in kebab-case
#   https://example.com:123/path
#   ^ - Empty path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
functions:
  - signature: Values(names []string) (values map[string]string)
    description: Values returns the values associated with the specified config property names for the caller microservice.
  - signature: Refresh()
    description: |-
      Refresh tells all microservices to contact the configurator and refresh their configs.
      An error is returned if any of the values sent to the microservices fails validation.
  - signature: Sync(timestamp time.Time, values map[string]map[string]string)
    description: Sync is used to synchronize values among replica peers of the configurator.
    queue: none

# Types
#
# name - All non-primitive types used in functions must be accounted for
# description - Documentation
# define - Define a new type with the specified fields (name: type)
# import - A path to another microservice that defines the type
types:
  # - name: DefinedType
  #   description:
  #   define:
  #     fieldName: Type
  # - name: ImportedType
  #   description:
  #   import: package/path/of/another/microservice

# Web handlers
#
# signature - Func()
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path
#   /directory/
#   :123/path
#   :123/... - Ellipsis denotes the function name in kebab-case
#   https://example.com:123/path
#   ^ - Empty path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
webs:
  # - signature:
  #   description:

# Tickers
#
# signature - Func()
# description - Documentation
# interval - Duration between iterations (e.g. 15m)
# timeBudget - Duration to complete an iteration
tickers:
  - signature: PeriodicRefresh()
    description: |-
      PeriodicRefresh tells all microservices to contact the configurator and refresh their configs.
      An error is returned if any of the values sent to the microservices fails validation.
    interval: 20m
