// Code generated by Microbus. DO NOT EDIT.

package blankapi

import (
    "time"
)

var (
    _ time.Duration
)

type User struct {
    FirstName string `json:"firstName"`
    LastName string `json:"lastName"`
    Balance int `json:"balance"`
}
