// Code generated by Microbus. DO NOT EDIT.

package blankapi

import (
	"context"
	"net/http"

	"github.com/microbus-io/fabric/errors"
	"github.com/microbus-io/fabric/pub"
)

/*
HelloWorld prints hello world
*/
func (_c *Client) HelloWorld(ctx context.Context, options ...pub.Option) (res *http.Response, err error) {
	opts := []pub.Option{
		pub.Method("POST"),
		pub.URL(joinHostAndPath(_c.host, `/helloworld`)),
	}
	opts = append(opts, options...)
	res, err = _c.svc.Request(ctx, opts...)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return res, err
}

func (_c *MulticastClient) HelloWorld(ctx context.Context, options ...pub.Option) <-chan *pub.Response {
	opts := []pub.Option{
		pub.Method("GET"),
		pub.URL(joinHostAndPath(_c.host, "/helloworld")),
	}
	opts = append(opts, options...)

	return _c.svc.Publish(ctx, opts...)
}
