/*
Copyright (c) 2023-2024 Microbus LLC and various contributors

This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
Neither may be used, copied or distributed without the express written consent of Microbus LLC.
*/

// Code generated by Microbus. DO NOT EDIT.

package httpingress

const Version = 234
const SourceCodeSHA256 = "57e3be3375e46ae14ed7d9609fd878e82aa0a6d5e399c219792b2a04fd05506d"
const Timestamp = "2024-06-07T14:53:16.853674Z"

/* {
	"ver": 234,
	"sha256": "57e3be3375e46ae14ed7d9609fd878e82aa0a6d5e399c219792b2a04fd05506d",
	"ts": "2024-06-07T14:53:16.853674Z"
} */
