/*
Copyright (c) 2023-2024 Microbus LLC and various contributors

This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
Neither may be used, copied or distributed without the express written consent of Microbus LLC.
*/

// Code generated by Microbus. DO NOT EDIT.

package openapiportal

const Version = 89
const SourceCodeSHA256 = "dce3467b275b8c152cbbf02259f56b78590d17bd2b28a909ea70d1a1088302ae"
const Timestamp = "2024-06-10T01:09:22.353919Z"

/* {
	"ver": 89,
	"sha256": "dce3467b275b8c152cbbf02259f56b78590d17bd2b28a909ea70d1a1088302ae",
	"ts": "2024-06-10T01:09:22.353919Z"
} */
