/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package svcapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/http"
	"reflect"

	"github.com/microbus-io/dv8"
	"github.com/microbus-io/dwarf/workflow"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
	"github.com/microbus-io/fabric/sub"
)

// multicastResponse packs the response of a functional multicast.
type multicastResponse struct {
	data         any
	HTTPResponse *http.Response
	err          error
}

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// WorkflowRunner executes a workflow by name with initial state, blocking until termination.
// foremanapi.Client satisfies this interface.
type WorkflowRunner interface {
	Run(ctx context.Context, workflowName string, initialState any, opts *workflow.FlowOptions) (outcome *workflow.FlowOutcome, err error)
}

// Executor runs tasks and workflows synchronously, blocking until termination.
// It is primarily intended for integration tests.
type Executor struct {
	svc         service.Publisher
	host        string
	opts        []pub.Option
	inFlow      *workflow.RawFlow
	outFlow     *workflow.Flow
	runner      WorkflowRunner
	flowOptions *workflow.FlowOptions
}

// NewExecutor creates a new executor proxy to the microservice.
func NewExecutor(caller service.Publisher) Executor {
	return Executor{svc: caller, host: Hostname}
}

// ForHost returns a copy of the executor with a different hostname to be applied to requests.
func (_c Executor) ForHost(host string) Executor {
	return Executor{svc: _c.svc, host: host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithOptions returns a copy of the executor with options to be applied to requests.
func (_c Executor) WithOptions(opts ...pub.Option) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...), inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithInputFlow returns a copy of the executor with an input flow to use for task execution.
// The input flow's state is available to the task in addition to the typed input arguments.
func (_c Executor) WithInputFlow(flow *workflow.RawFlow) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: flow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithOutputFlow returns a copy of the executor with an output flow to populate after task execution.
// The output flow captures the full flow state including control signals (Goto, Retry, Interrupt, Sleep).
func (_c Executor) WithOutputFlow(flow *workflow.Flow) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: flow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithWorkflowRunner returns a copy of the executor with a workflow runner for executing workflows.
// foremanapi.NewClient(svc) satisfies the WorkflowRunner interface.
func (_c Executor) WithWorkflowRunner(runner WorkflowRunner) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: runner, flowOptions: _c.flowOptions}
}

// WithFlowOptions returns a copy of the executor that creates workflows with the given flow options
// (priority, fairness key and weight). It has no effect on task execution.
func (_c Executor) WithFlowOptions(flowOptions *workflow.FlowOptions) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: flowOptions}
}

// Subgraph runs this microservice's workflows from inside a task body. Create it with
// NewSubgraph(flow), then call the method named after the workflow you want to invoke.
type Subgraph struct {
	flow *workflow.Flow
}

// NewSubgraph creates a subgraph client bound to the calling task's flow carrier.
func NewSubgraph(flow *workflow.Flow) Subgraph {
	return Subgraph{flow: flow}
}

// MulticastTrigger is a lightweight proxy for triggering the events of the microservice.
type MulticastTrigger struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastTrigger creates a new multicast trigger of events of the microservice.
func NewMulticastTrigger(caller service.Publisher) MulticastTrigger {
	return MulticastTrigger{svc: caller, host: Hostname}
}

// ForHost returns a copy of the trigger with a different hostname to be applied to requests.
func (_c MulticastTrigger) ForHost(host string) MulticastTrigger {
	return MulticastTrigger{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the trigger with options to be applied to requests.
func (_c MulticastTrigger) WithOptions(opts ...pub.Option) MulticastTrigger {
	return MulticastTrigger{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// Hook assists in the subscription to the events of the microservice.
type Hook struct {
	svc  service.Subscriber
	host string
	opts []sub.Option
}

// NewHook creates a new hook to the events of the microservice.
func NewHook(listener service.Subscriber) Hook {
	return Hook{svc: listener, host: Hostname}
}

// ForHost returns a copy of the hook with a different hostname to be applied to the subscription.
func (c Hook) ForHost(host string) Hook {
	return Hook{svc: c.svc, host: host, opts: c.opts}
}

// WithOptions returns a copy of the hook with options to be applied to subscriptions.
func (c Hook) WithOptions(opts ...sub.Option) Hook {
	return Hook{svc: c.svc, host: c.host, opts: append(c.opts, opts...)}
}

// marshalRequest supports functional endpoints.
func marshalRequest(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) (err error) {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return err // No trace
	}
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = httpx.ReadOutputPayload(httpRes, out)
	return errors.Trace(err)
}

// marshalPublish supports multicast functional endpoints.
func marshalPublish(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) iter.Seq[*multicastResponse] {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return func(yield func(*multicastResponse) bool) {
			yield(&multicastResponse{err: err})
		}
	}
	_queue := svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	return func(yield func(*multicastResponse) bool) {
		for qi := range _queue {
			httpResp, err := qi.Get()
			if err == nil {
				reflect.ValueOf(out).Elem().SetZero()
				err = httpx.ReadOutputPayload(httpResp, out)
			}
			if err != nil {
				if !yield(&multicastResponse{err: err, HTTPResponse: httpResp}) {
					return
				}
			} else {
				if !yield(&multicastResponse{data: out, HTTPResponse: httpResp}) {
					return
				}
			}
		}
	}
}

// marshalFunction handles marshaling for functional endpoints.
func marshalFunction(w http.ResponseWriter, r *http.Request, route string, in any, out any, execute func(in any, out any) error) error {
	err := httpx.ReadInputPayload(r, route, in)
	if err != nil {
		return errors.Trace(err)
	}
	// The body is fully decoded into the input, so release it for the duration of the handler
	r.Body = http.NoBody
	err = dv8.Validate(r.Context(), in)
	if err != nil {
		return errors.Trace(err)
	}
	err = execute(in, out)
	if err != nil {
		return err // No trace
	}
	err = httpx.WriteOutputPayload(w, out)
	if err != nil {
		return errors.Trace(err)
	}
	return nil
}

// marshalTask supports task execution via the Executor.
func marshalTask(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any, inFlow *workflow.RawFlow, outFlow *workflow.Flow) (err error) {
	flow := inFlow
	if flow == nil {
		flow = workflow.NewRawFlow()
	}
	inState, err := workflow.NewState(in)
	if err != nil {
		return errors.Trace(err)
	}
	state := flow.RawState()
	err = state.Merge(inState)
	if err != nil {
		return errors.Trace(err)
	}
	flow.SetRawState(state)
	body, err := json.Marshal(flow)
	if err != nil {
		return errors.Trace(err)
	}
	u := httpx.JoinHostAndPath(host, route)
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Body(body),
		pub.ContentType("application/json"),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = json.NewDecoder(httpRes.Body).Decode(flow)
	if err != nil {
		return errors.Trace(err)
	}
	if outFlow != nil {
		*outFlow = flow.Flow
	}
	if out != nil {
		err = flow.ParseState(out)
		return errors.Trace(err)
	}
	return nil
}

// marshalWorkflow supports workflow execution via the Executor.
func marshalWorkflow(ctx context.Context, runner WorkflowRunner, flowOptions *workflow.FlowOptions, workflowURL string, in any, out any) (status string, err error) {
	outcome, err := runner.Run(ctx, workflowURL, in, flowOptions)
	if err != nil {
		if outcome != nil {
			return outcome.Status, err // No trace
		}
		return "", err // No trace
	}
	if outcome == nil {
		return "", nil
	}
	status = outcome.Status
	if out != nil {
		err = outcome.State.Parse(out)
		if err != nil {
			return status, errors.Trace(err)
		}
	}
	return status, nil
}

// marshalSubgraph runs a child workflow via the flow carrier and returns the parker's yield.
func marshalSubgraph(flow *workflow.Flow, url string, in any, out any) (yield bool, err error) {
	if flow == nil {
		return false, errors.New("Subgraph requires a flow carrier (call from a task body)")
	}
	return flow.Subgraph(url, in, out)
}

// DoThing performs a thing and exercises claims and a time budget.
func (_c Client) DoThing(ctx context.Context, name string, count int) (result string, err error) { // MARKER: DoThing
	_in := DoThingIn{Name: name, Count: count}
	_out := DoThingOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, DoThing.Method, DoThing.Route, &_in, &_out)
	return _out.Result, err // No trace
}

// DoThingResponse packs the response of DoThing.
type DoThingResponse multicastResponse // MARKER: DoThing

// Get unpacks the return arguments of DoThing.
func (_res *DoThingResponse) Get() (result string, err error) { // MARKER: DoThing
	_d := _res.data.(*DoThingOut)
	return _d.Result, _res.err
}

// DoThing performs a thing and exercises claims and a time budget.
func (_c MulticastClient) DoThing(ctx context.Context, name string, count int) iter.Seq[*DoThingResponse] { // MARKER: DoThing
	_in := DoThingIn{Name: name, Count: count}
	_out := DoThingOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, DoThing.Method, DoThing.Route, &_in, &_out)
	return func(yield func(*DoThingResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*DoThingResponse)(_r)) {
				return
			}
		}
	}
}

// CreatePet exercises the httpRequestBody / httpStatusCode magic arguments (REST create).
func (_c Client) CreatePet(ctx context.Context, httpRequestBody *Pet) (key string, httpStatusCode int, err error) { // MARKER: CreatePet
	_in := CreatePetIn{HTTPRequestBody: httpRequestBody}
	_out := CreatePetOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, CreatePet.Method, CreatePet.Route, &_in, &_out)
	return _out.Key, _out.HTTPStatusCode, err // No trace
}

// CreatePetResponse packs the response of CreatePet.
type CreatePetResponse multicastResponse // MARKER: CreatePet

// Get unpacks the return arguments of CreatePet.
func (_res *CreatePetResponse) Get() (key string, httpStatusCode int, err error) { // MARKER: CreatePet
	_d := _res.data.(*CreatePetOut)
	return _d.Key, _d.HTTPStatusCode, _res.err
}

// CreatePet exercises the httpRequestBody / httpStatusCode magic arguments (REST create).
func (_c MulticastClient) CreatePet(ctx context.Context, httpRequestBody *Pet) iter.Seq[*CreatePetResponse] { // MARKER: CreatePet
	_in := CreatePetIn{HTTPRequestBody: httpRequestBody}
	_out := CreatePetOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, CreatePet.Method, CreatePet.Route, &_in, &_out)
	return func(yield func(*CreatePetResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*CreatePetResponse)(_r)) {
				return
			}
		}
	}
}

// LoadPet exercises the httpResponseBody / httpStatusCode magic arguments (REST load).
func (_c Client) LoadPet(ctx context.Context, petID int64) (httpResponseBody *Pet, httpStatusCode int, err error) { // MARKER: LoadPet
	_in := LoadPetIn{PetID: petID}
	_out := LoadPetOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, LoadPet.Method, LoadPet.Route, &_in, &_out)
	return _out.HTTPResponseBody, _out.HTTPStatusCode, err // No trace
}

// LoadPetResponse packs the response of LoadPet.
type LoadPetResponse multicastResponse // MARKER: LoadPet

// Get unpacks the return arguments of LoadPet.
func (_res *LoadPetResponse) Get() (httpResponseBody *Pet, httpStatusCode int, err error) { // MARKER: LoadPet
	_d := _res.data.(*LoadPetOut)
	return _d.HTTPResponseBody, _d.HTTPStatusCode, _res.err
}

// LoadPet exercises the httpResponseBody / httpStatusCode magic arguments (REST load).
func (_c MulticastClient) LoadPet(ctx context.Context, petID int64) iter.Seq[*LoadPetResponse] { // MARKER: LoadPet
	_in := LoadPetIn{PetID: petID}
	_out := LoadPetOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, LoadPet.Method, LoadPet.Route, &_in, &_out)
	return func(yield func(*LoadPetResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*LoadPetResponse)(_r)) {
				return
			}
		}
	}
}

// SelfPing is an internal-only endpoint that multicasts to all peers (no queue).
func (_c Client) SelfPing(ctx context.Context) (err error) { // MARKER: SelfPing
	_in := SelfPingIn{}
	_out := SelfPingOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, SelfPing.Method, SelfPing.Route, &_in, &_out)
	return err // No trace
}

// SelfPingResponse packs the response of SelfPing.
type SelfPingResponse multicastResponse // MARKER: SelfPing

// Get unpacks the return arguments of SelfPing.
func (_res *SelfPingResponse) Get() (err error) { // MARKER: SelfPing
	return _res.err
}

// SelfPing is an internal-only endpoint that multicasts to all peers (no queue).
func (_c MulticastClient) SelfPing(ctx context.Context) iter.Seq[*SelfPingResponse] { // MARKER: SelfPing
	_in := SelfPingIn{}
	_out := SelfPingOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, SelfPing.Method, SelfPing.Route, &_in, &_out)
	return func(yield func(*SelfPingResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*SelfPingResponse)(_r)) {
				return
			}
		}
	}
}

// AltHost registers on a non-own host via the //host:port/path form.
func (_c Client) AltHost(ctx context.Context) (err error) { // MARKER: AltHost
	_in := AltHostIn{}
	_out := AltHostOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, AltHost.Method, AltHost.Route, &_in, &_out)
	return err // No trace
}

// AltHostResponse packs the response of AltHost.
type AltHostResponse multicastResponse // MARKER: AltHost

// Get unpacks the return arguments of AltHost.
func (_res *AltHostResponse) Get() (err error) { // MARKER: AltHost
	return _res.err
}

// AltHost registers on a non-own host via the //host:port/path form.
func (_c MulticastClient) AltHost(ctx context.Context) iter.Seq[*AltHostResponse] { // MARKER: AltHost
	_in := AltHostIn{}
	_out := AltHostOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, AltHost.Method, AltHost.Route, &_in, &_out)
	return func(yield func(*AltHostResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*AltHostResponse)(_r)) {
				return
			}
		}
	}
}

// Dashboard serves an HTML dashboard on any method.
func (_c Client) Dashboard(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Dashboard
	if method == "" {
		method = Dashboard.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Dashboard.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Dashboard serves an HTML dashboard on any method.
func (_c MulticastClient) Dashboard(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Dashboard
	if method == "" {
		method = Dashboard.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Dashboard.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// ProcessStep is a workflow task that transforms state.
func (_c Executor) ProcessStep(ctx context.Context, item Item) (processed bool, err error) { // MARKER: ProcessStep
	var out ProcessStepOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, ProcessStep.Method, ProcessStep.Route, ProcessStepIn{Item: item}, &out, _c.inFlow, _c.outFlow)
	return out.Processed, err // No trace
}

// ReviewStep is a workflow task whose output reads-modifies-writes the shared "count" state field,
// exercising the xxxOut suffix convention (Go field CountOut, JSON tag count).
func (_c Executor) ReviewStep(ctx context.Context, count int) (countOut int, err error) { // MARKER: ReviewStep
	var out ReviewStepOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, ReviewStep.Method, ReviewStep.Route, ReviewStepIn{Count: count}, &out, _c.inFlow, _c.outFlow)
	return out.CountOut, err // No trace
}

// MainFlow is the top-level workflow graph.
func (_c Executor) MainFlow(ctx context.Context, item Item) (done bool, status string, err error) { // MARKER: MainFlow
	if _c.runner == nil {
		return done, "", errors.New("workflow runner not set, use WithWorkflowRunner")
	}
	var out MainFlowOut
	status, err = marshalWorkflow(ctx, _c.runner, _c.flowOptions, MainFlow.URL(), MainFlowIn{Item: item}, &out)
	return out.Done, status, err
}

// MainFlow is the top-level workflow graph.
func (_sg Subgraph) MainFlow(ctx context.Context, item Item) (done bool, yield bool, err error) { // MARKER: MainFlow
	var out MainFlowOut
	yield, err = marshalSubgraph(_sg.flow, MainFlow.URL(), MainFlowIn{Item: item}, &out)
	if yield || err != nil {
		return done, yield, err
	}
	return out.Done, false, nil
}

// OnLocalEventResponse packs the response of OnLocalEvent.
type OnLocalEventResponse multicastResponse // MARKER: OnLocalEvent

// Get unpacks the return arguments of OnLocalEvent.
func (_res *OnLocalEventResponse) Get() (ack bool, err error) { // MARKER: OnLocalEvent
	_d := _res.data.(*OnLocalEventOut)
	return _d.Ack, _res.err
}

// OnLocalEvent fires when this microservice completes a local action.
func (_c MulticastTrigger) OnLocalEvent(ctx context.Context, note string) iter.Seq[*OnLocalEventResponse] { // MARKER: OnLocalEvent
	_in := OnLocalEventIn{Note: note}
	_out := OnLocalEventOut{}
	_inner := marshalPublish(ctx, _c.svc, _c.opts, _c.host, OnLocalEvent.Method, OnLocalEvent.Route, &_in, &_out)
	return func(yield func(*OnLocalEventResponse) bool) {
		for _r := range _inner {
			_clone := _out
			_r.data = &_clone
			if !yield((*OnLocalEventResponse)(_r)) {
				return
			}
		}
	}
}

// OnLocalEvent fires when this microservice completes a local action.
func (c Hook) OnLocalEvent(handler func(ctx context.Context, note string) (ack bool, err error)) (unsub func() error, err error) { // MARKER: OnLocalEvent
	doOnLocalEvent := func(w http.ResponseWriter, r *http.Request) error {
		var in OnLocalEventIn
		var out OnLocalEventOut
		err = marshalFunction(w, r, OnLocalEvent.Route, &in, &out, func(_ any, _ any) error {
			out.Ack, err = handler(r.Context(), in.Note)
			return err
		})
		return err // No trace
	}
	const name = "OnLocalEvent"
	path := httpx.JoinHostAndPath(c.host, OnLocalEvent.Route)
	subOpts := append([]sub.Option{
		sub.At(OnLocalEvent.Method, path),
		sub.InboundEvent(OnLocalEventIn{}, OnLocalEventOut{}),
	}, c.opts...)
	if err := c.svc.Subscribe(name, doOnLocalEvent, subOpts...); err != nil {
		return nil, errors.Trace(err)
	}
	return func() error { return c.svc.Unsubscribe(name) }, nil
}
