/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package eventsource

import (
	"context"
	"net/http"

	"github.com/microbus-io/dv8"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/exampleservices/eventsource/eventsourceapi"
	"github.com/microbus-io/fabric/exampleservices/eventsource/resources"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
)

const (
	Hostname    = eventsourceapi.Hostname
	Version     = eventsourceapi.Version
	Description = eventsourceapi.Description
)

// ToDo is implemented by the service or mock.
// The intermediate delegates handling to this interface.
type ToDo interface {
	OnStartup(ctx context.Context) (err error)
	OnShutdown(ctx context.Context) (err error)
	Register(ctx context.Context, email string) (allowed bool, err error) // MARKER: Register
}

// NewService creates a new instance of the microservice.
func NewService() *Service {
	svc := &Service{}
	svc.Intermediate = NewIntermediate(svc)
	return svc
}

// Init enables a single-statement pattern for initializing the microservice.
func (svc *Service) Init(initializer func(svc *Service) (err error)) *Service {
	svc.Connector.Init(func(_ *connector.Connector) (err error) {
		return initializer(svc)
	})
	return svc
}

// Intermediate extends and customizes the generic base connector.
type Intermediate struct {
	*connector.Connector
	ToDo
}

// NewIntermediate creates a new instance of the intermediate.
func NewIntermediate(impl ToDo) *Intermediate {
	svc := &Intermediate{
		Connector: connector.New(Hostname),
		ToDo:      impl,
	}
	svc.SetVersion(Version)
	svc.SetDescription(Description)
	svc.SetOnStartup(svc.OnStartup)
	svc.SetOnShutdown(svc.OnShutdown)
	svc.SetResFS(resources.FS)
	svc.SetOnObserveMetrics(svc.doOnObserveMetrics)
	svc.SetOnConfigChanged(svc.doOnConfigChanged)

	svc.Connector.Init(func(_ *connector.Connector) (err error) {
		// Fail startup on a malformed validation directive in an endpoint input type
		return dv8.Compile(
			eventsourceapi.RegisterIn{}, // MARKER: Register
		)
	})

	svc.Subscribe( // MARKER: Register
		"Register", svc.doRegister,
		sub.At(eventsourceapi.Register.Method, eventsourceapi.Register.Route),
		sub.Description(`Register attempts to register a new user.`),
		sub.Function(eventsourceapi.RegisterIn{}, eventsourceapi.RegisterOut{}),
	)

	return svc
}

// doOnObserveMetrics is called when metrics are produced.
func (svc *Intermediate) doOnObserveMetrics(ctx context.Context) (err error) {
	return svc.Parallel(ctx)
}

// doOnConfigChanged is called when the config of the microservice changes.
func (svc *Intermediate) doOnConfigChanged(ctx context.Context, changed func(string) bool) (err error) {
	return nil
}

// marshalFunction handles marshaling for functional endpoints.
func marshalFunction(w http.ResponseWriter, r *http.Request, route string, in any, out any, execute func(in any, out any) error) error {
	err := httpx.ReadInputPayload(r, route, in)
	if err != nil {
		return errors.Trace(err)
	}
	// The body is fully decoded into the input, so release it for the duration of the handler
	r.Body = http.NoBody
	err = dv8.Validate(r.Context(), in)
	if err != nil {
		return errors.Trace(err)
	}
	err = execute(in, out)
	if err != nil {
		return err // No trace
	}
	err = httpx.WriteOutputPayload(w, out)
	if err != nil {
		return errors.Trace(err)
	}
	return nil
}

// doRegister handles marshaling for Register.
func (svc *Intermediate) doRegister(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: Register
	var in eventsourceapi.RegisterIn
	var out eventsourceapi.RegisterOut
	err = marshalFunction(w, r, eventsourceapi.Register.Route, &in, &out, func(_ any, _ any) error {
		out.Allowed, err = svc.Register(r.Context(), in.Email)
		return err // No trace
	})
	return err // No trace
}
