/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package bearertokenapi

import (
	"context"
	"iter"
	"net/http"
	"reflect"

	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
)

// multicastResponse packs the response of a functional multicast.
type multicastResponse struct {
	data         any
	HTTPResponse *http.Response
	err          error
}

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// marshalRequest supports functional endpoints.
func marshalRequest(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) (err error) {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return err // No trace
	}
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = httpx.ReadOutputPayload(httpRes, out)
	return errors.Trace(err)
}

// marshalPublish supports multicast functional endpoints.
func marshalPublish(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any) iter.Seq[*multicastResponse] {
	if method == "ANY" {
		method = "POST"
	}
	u := httpx.JoinHostAndPath(host, route)
	query, body, err := httpx.WriteInputPayload(method, in)
	if err != nil {
		return func(yield func(*multicastResponse) bool) {
			yield(&multicastResponse{err: err})
		}
	}
	_queue := svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Query(query),
		pub.Body(body),
		pub.Options(opts...),
	)
	return func(yield func(*multicastResponse) bool) {
		for qi := range _queue {
			httpResp, err := qi.Get()
			if err == nil {
				reflect.ValueOf(out).Elem().SetZero()
				err = httpx.ReadOutputPayload(httpResp, out)
			}
			if err != nil {
				if !yield(&multicastResponse{err: err, HTTPResponse: httpResp}) {
					return
				}
			} else {
				if !yield(&multicastResponse{data: out, HTTPResponse: httpResp}) {
					return
				}
			}
		}
	}
}

// Mint signs a JWT with the given claims.
func (_c Client) Mint(ctx context.Context, claims any) (token string, err error) { // MARKER: Mint
	_in := MintIn{Claims: claims}
	_out := MintOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, Mint.Method, Mint.Route, &_in, &_out)
	return _out.Token, err // No trace
}

// MintResponse packs the response of Mint.
type MintResponse multicastResponse // MARKER: Mint

// Get unpacks the return arguments of Mint.
func (_res *MintResponse) Get() (token string, err error) { // MARKER: Mint
	_d := _res.data.(*MintOut)
	return _d.Token, _res.err
}

// Mint signs a JWT with the given claims.
func (_c MulticastClient) Mint(ctx context.Context, claims any) iter.Seq[*MintResponse] { // MARKER: Mint
	_in := MintIn{Claims: claims}
	_out := MintOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, Mint.Method, Mint.Route, &_in, &_out)
	return func(yield func(*MintResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*MintResponse)(_r)) {
				return
			}
		}
	}
}

// JWKS returns the public keys of the token issuer in JWKS format.
// Callers may cache the response, or debounce fetches to this endpoint, for up to 1 second.
func (_c Client) JWKS(ctx context.Context) (keys []JWK, err error) { // MARKER: JWKS
	_in := JWKSIn{}
	_out := JWKSOut{}
	err = marshalRequest(ctx, _c.svc, _c.opts, _c.host, JWKS.Method, JWKS.Route, &_in, &_out)
	return _out.Keys, err // No trace
}

// JWKSResponse packs the response of JWKS.
type JWKSResponse multicastResponse // MARKER: JWKS

// Get unpacks the return arguments of JWKS.
func (_res *JWKSResponse) Get() (keys []JWK, err error) { // MARKER: JWKS
	_d := _res.data.(*JWKSOut)
	return _d.Keys, _res.err
}

// JWKS returns the public keys of the token issuer in JWKS format.
// Callers may cache the response, or debounce fetches to this endpoint, for up to 1 second.
func (_c MulticastClient) JWKS(ctx context.Context) iter.Seq[*JWKSResponse] { // MARKER: JWKS
	_in := JWKSIn{}
	_out := JWKSOut{}
	_queue := marshalPublish(ctx, _c.svc, _c.opts, _c.host, JWKS.Method, JWKS.Route, &_in, &_out)
	return func(yield func(*JWKSResponse) bool) {
		for _r := range _queue {
			_clone := _out
			_r.data = &_clone
			if !yield((*JWKSResponse)(_r)) {
				return
			}
		}
	}
}
