// Code generated by Microbus. DO NOT EDIT.

package messaging

const Version = 3
const SourceCodeSHA256 = "04dee1e06037dc945a71cd14439e0ae40c0660a479b570dc675bbea8999559bd"
const Timestamp = "2022-11-06T21:24:46.185176Z"

/* {
	"ver": 3,
	"sha256": "04dee1e06037dc945a71cd14439e0ae40c0660a479b570dc675bbea8999559bd",
	"ts": "2022-11-06T21:24:46.185176Z"
} */
