---
# General
#
# host - The host name of the microservice
# description - A human-friendly description of the microservice
# integrationTests - Whether or not to generate integration tests (defaults to true)
general:
  host: control.sys
  description: |-
    This microservice is created for the sake of generating the client API for the :888 control subscriptions.
    The microservice itself does nothing and should not be included in applications.
  integrationTests: false

# Config properties
#
# signature - Func() (val Type)
# description - Documentation
# default - A default value (defaults to empty)
# validation - A validation pattern
#   str ^[a-zA-Z0-9]+$
#   bool
#   int [0,60]
#   float [0.0,1.0)
#   dur (0s,24h]
#   set Red|Green|Blue
#   url
#   email
#   json
# callback - "true" to handle the change event (defaults to "false")
# secret - "true" to indicate a secret (defaults to "false")
configs:
  # - signature:
  #   description:
  #   default:
  #   validation:

# Functions
#
# signature - Func(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :443
#   /directory/ - All paths under the directory
#   :443/path
#   :443/... - Ellipsis denotes the function name in kebab-case
#   :443 - Root path
#   https://example.com:443/path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
functions:
  - signature: Ping() (pong int)
    path: :888/...
    description: Ping responds to the message with a pong.
  - signature: ConfigRefresh()
    path: :888/...
    description: ConfigRefresh pulls the latest config values from the configurator service.

# Types
#
# name - All non-primitive types used in functions must be accounted for
# description - Documentation
# define - Define a new type with the specified fields (name: type)
# import - The package path of the imported type
types:
  # - name: DefinedType
  #   description:
  #   define:
  #     fieldName: Type
  # - name: ImportedType
  #   description:
  #   import: package/path/of/a/remote/type/ImportedType

# Web handlers
#
# signature - Func()
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :443
#   /directory/ - All paths under the directory
#   :443/path
#   :443/... - Ellipsis denotes the function name in kebab-case
#   :443 - Root path
#   https://example.com:443/path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
webs:
  # - signature:
  #   description:

# Tickers
#
# signature - Func()
# description - Documentation
# interval - Duration between iterations (e.g. 15m)
# timeBudget - Duration to complete an iteration
tickers:
  # - signature:
  #   description:
  #   interval:

# Event sources
#
# signature - OnFunc(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path - Default port :417
#   /directory/ - All paths under the directory
#   :417/path
#   :417/... - Ellipsis denotes the function name in kebab-case
#   :417 - Root path
#   https://example.com:417/path
events:
  # - signature:
  #   description:

# Event sinks
#
# signature - OnFunc(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# event - The name of the event at the source (defaults to the function name)
# source - The package path of the microservice that is the source of the event
# forHost - For an event source with an overridden host name
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
sinks:
  # - signature:
  #   description:
  #   source: package/path/of/another/microservice

# Databases
#
# mysql - A name for the MySQL database
databases:
