---
# General
#
# host - The host name of the microservice
# description - A human-friendly description of the microservice
general:
  host: control.sys
  description: |-
    This microservice is created for the sake of generating the client API for the :888 control subscriptions.
    The microservice itself does nothing and should not be included in applications.

# Config properties
#
# signature - Func() (val Type)
# description - Documentation
# default - A default value (defaults to empty)
# validation - A validation pattern
#   str ^[a-zA-Z0-9]+$
#   bool
#   int [0,60]
#   float [0.0,1.0)
#   dur (0s,24h]
#   set Red|Green|Blue
#   url
#   email
#   json
# callback - "true" to handle the change event (defaults to "false")
# secret - "true" to indicate a secret (defaults to "false")
configs:
  # - signature:
  #   description:
  #   default:
  #   validation:

# Functions
#
# signature - Func(name Type, name Type) (name Type, name Type, httpStatusCode int)
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path
#   /directory/
#   :123/path
#   :123/... - Ellipsis denotes the function name in kebab-case
#   https://example.com:123/path
#   ^ - Empty path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
functions:
  - signature: Ping() (pong int)
    path: :888/...
    description: Ping responds to the message with a pong.
  - signature: ConfigRefresh()
    path: :888/...
    description: ConfigRefresh pulls the latest config values from the configurator service.

# Types
#
# name - All non-primitive types used in functions must be accounted for
# description - Documentation
# define - Define a new type with the specified fields (name: type)
# import - A path to another microservice that defines the type
types:
  # - name: DefinedType
  #   description:
  #   define:
  #     fieldName: Type
  # - name: ImportedType
  #   description:
  #   import: package/path/of/another/microservice

# Web handlers
#
# signature - Func()
# description - Documentation
# path - The subscription path
#   (empty) - The function name in kebab-case
#   /path
#   /directory/
#   :123/path
#   :123/... - Ellipsis denotes the function name in kebab-case
#   https://example.com:123/path
#   ^ - Empty path
# queue - The subscription queue
#   default - Load balanced (default)
#   none - Pervasive
webs:
  # - signature:
  #   description:

# Tickers
#
# signature - Func()
# description - Documentation
# interval - Duration between iterations (e.g. 15m)
# timeBudget - Duration to complete an iteration
tickers:
  # - signature:
  #   description:
  #   interval:
