// Code generated by Microbus. DO NOT EDIT.

package control

const Version = 37
const SourceCodeSHA256 = "5b6882990d197dff78a447cfdfa6c0e3dcb35668fc7e448c0acffa0f8e38122b"
const Timestamp = "2023-01-13T00:18:58.981638Z"

/* {
	"ver": 37,
	"sha256": "5b6882990d197dff78a447cfdfa6c0e3dcb35668fc7e448c0acffa0f8e38122b",
	"ts": "2023-01-13T00:18:58.981638Z"
} */
