/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package geminillm

import (
	"context"
	"net/http"
	"time"

	"github.com/microbus-io/dv8"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/cfg"
	"github.com/microbus-io/fabric/connector"
	"github.com/microbus-io/fabric/coreservices/geminillm/geminillmapi"
	"github.com/microbus-io/fabric/coreservices/geminillm/resources"
	"github.com/microbus-io/fabric/coreservices/llm/llmapi"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/sub"
)

const (
	Hostname    = geminillmapi.Hostname
	Version     = geminillmapi.Version
	Description = geminillmapi.Description
)

// ToDo is implemented by the service or mock.
// The intermediate delegates handling to this interface.
type ToDo interface {
	OnStartup(ctx context.Context) (err error)
	OnShutdown(ctx context.Context) (err error)
	Turn(ctx context.Context, model string, items []llmapi.Item, tools []llmapi.Tool, options *llmapi.TurnOptions) (itemsOut []llmapi.Item, stopReason string, usage llmapi.Usage, err error) // MARKER: Turn
	OnResolveProvider(ctx context.Context, model string) (ok bool, err error)                                                                                                                 // MARKER: OnResolveProvider
	RefreshModels(ctx context.Context) (err error)                                                                                                                                            // MARKER: RefreshModels
}

// NewService creates a new instance of the microservice.
func NewService() *Service {
	svc := &Service{}
	svc.Intermediate = NewIntermediate(svc)
	return svc
}

// Init enables a single-statement pattern for initializing the microservice.
func (svc *Service) Init(initializer func(svc *Service) (err error)) *Service {
	svc.Connector.Init(func(_ *connector.Connector) (err error) {
		return initializer(svc)
	})
	return svc
}

// Intermediate extends and customizes the generic base connector.
type Intermediate struct {
	*connector.Connector
	ToDo
}

// NewIntermediate creates a new instance of the intermediate.
func NewIntermediate(impl ToDo) *Intermediate {
	svc := &Intermediate{
		Connector: connector.New(Hostname),
		ToDo:      impl,
	}
	svc.SetVersion(Version)
	svc.SetDescription(Description)
	svc.SetOnStartup(svc.OnStartup)
	svc.SetOnShutdown(svc.OnShutdown)
	svc.SetResFS(resources.FS)
	svc.SetOnObserveMetrics(svc.doOnObserveMetrics)
	svc.SetOnConfigChanged(svc.doOnConfigChanged)

	svc.Connector.Init(func(_ *connector.Connector) (err error) {
		// Fail startup on a malformed validation directive in an endpoint input type
		return dv8.Compile(
			geminillmapi.TurnIn{},        // MARKER: Turn
			llmapi.OnResolveProviderIn{}, // MARKER: OnResolveProvider
		)
	})

	svc.Subscribe( // MARKER: Turn
		"Turn", svc.doTurn,
		sub.At(geminillmapi.Turn.Method, geminillmapi.Turn.Route),
		sub.Description(`Turn executes a single LLM turn using the Gemini provider.`),
		sub.Function(geminillmapi.TurnIn{}, geminillmapi.TurnOut{}),
	)
	llmapi.NewHook(svc).OnResolveProvider(svc.OnResolveProvider)     // MARKER: OnResolveProvider
	svc.StartTicker("RefreshModels", 6*time.Hour, svc.RefreshModels) // MARKER: RefreshModels
	svc.DefineConfig(                                                // MARKER: ModelsURL
		"ModelsURL",
		cfg.Description(`ModelsURL is the base URL of the Gemini models endpoint; the model and action (generateContent, countTokens) are appended per request.`),
		cfg.DefaultValue(`https://generativelanguage.googleapis.com/v1beta/models`),
		cfg.Validation(`url`),
	)
	svc.DefineConfig( // MARKER: APIKey
		"APIKey",
		cfg.Description(`APIKey is the API key for the Gemini API.`),
		cfg.Secret(),
	)

	return svc
}

// doOnObserveMetrics is called when metrics are produced.
func (svc *Intermediate) doOnObserveMetrics(ctx context.Context) (err error) {
	return svc.Parallel(ctx)
}

// doOnConfigChanged is called when the config of the microservice changes.
func (svc *Intermediate) doOnConfigChanged(ctx context.Context, changed func(string) bool) (err error) {
	return nil
}

// marshalFunction handles marshaling for functional endpoints.
func marshalFunction(w http.ResponseWriter, r *http.Request, route string, in any, out any, execute func(in any, out any) error) error {
	err := httpx.ReadInputPayload(r, route, in)
	if err != nil {
		return errors.Trace(err)
	}
	err = dv8.Validate(r.Context(), in)
	if err != nil {
		return errors.Trace(err)
	}
	err = execute(in, out)
	if err != nil {
		return err // No trace
	}
	err = httpx.WriteOutputPayload(w, out)
	if err != nil {
		return errors.Trace(err)
	}
	return nil
}

// doTurn handles marshaling for Turn.
func (svc *Intermediate) doTurn(w http.ResponseWriter, r *http.Request) (err error) { // MARKER: Turn
	var in geminillmapi.TurnIn
	var out geminillmapi.TurnOut
	err = marshalFunction(w, r, geminillmapi.Turn.Route, &in, &out, func(_ any, _ any) error {
		out.ItemsOut, out.StopReason, out.Usage, err = svc.Turn(r.Context(), in.Model, in.Items, in.Tools, in.Options)
		return err // No trace
	})
	return err // No trace
}

// ModelsURL is the base URL of the Gemini models endpoint; the model and action (generateContent, countTokens) are appended per request.
func (svc *Intermediate) ModelsURL() (value string) { // MARKER: ModelsURL
	return svc.Config("ModelsURL")
}

// SetModelsURL sets the value of the configuration property.
func (svc *Intermediate) SetModelsURL(value string) (err error) { // MARKER: ModelsURL
	return svc.SetConfig("ModelsURL", value)
}

// APIKey is the API key for the Gemini API.
func (svc *Intermediate) APIKey() (value string) { // MARKER: APIKey
	return svc.Config("APIKey")
}

// SetAPIKey sets the value of the configuration property.
func (svc *Intermediate) SetAPIKey(value string) (err error) { // MARKER: APIKey
	return svc.SetConfig("APIKey", value)
}
