/*
Copyright (c) 2023-2026 Microbus LLC and various contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cmd/genservice. DO NOT EDIT.

package creditflowapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/http"

	"github.com/microbus-io/dwarf/workflow"
	"github.com/microbus-io/errors"
	"github.com/microbus-io/fabric/httpx"
	"github.com/microbus-io/fabric/pub"
	"github.com/microbus-io/fabric/service"
)

// Client is a lightweight proxy for making unicast calls to the microservice.
type Client struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewClient creates a new unicast client proxy to the microservice.
func NewClient(caller service.Publisher) Client {
	return Client{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c Client) ForHost(host string) Client {
	return Client{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c Client) WithOptions(opts ...pub.Option) Client {
	return Client{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// MulticastClient is a lightweight proxy for making multicast calls to the microservice.
type MulticastClient struct {
	svc  service.Publisher
	host string
	opts []pub.Option
}

// NewMulticastClient creates a new multicast client proxy to the microservice.
func NewMulticastClient(caller service.Publisher) MulticastClient {
	return MulticastClient{svc: caller, host: Hostname}
}

// ForHost returns a copy of the client with a different hostname to be applied to requests.
func (_c MulticastClient) ForHost(host string) MulticastClient {
	return MulticastClient{svc: _c.svc, host: host, opts: _c.opts}
}

// WithOptions returns a copy of the client with options to be applied to requests.
func (_c MulticastClient) WithOptions(opts ...pub.Option) MulticastClient {
	return MulticastClient{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...)}
}

// WorkflowRunner executes a workflow by name with initial state, blocking until termination.
// foremanapi.Client satisfies this interface.
type WorkflowRunner interface {
	Run(ctx context.Context, workflowName string, initialState any, opts *workflow.FlowOptions) (outcome *workflow.FlowOutcome, err error)
}

// Executor runs tasks and workflows synchronously, blocking until termination.
// It is primarily intended for integration tests.
type Executor struct {
	svc         service.Publisher
	host        string
	opts        []pub.Option
	inFlow      *workflow.RawFlow
	outFlow     *workflow.Flow
	runner      WorkflowRunner
	flowOptions *workflow.FlowOptions
}

// NewExecutor creates a new executor proxy to the microservice.
func NewExecutor(caller service.Publisher) Executor {
	return Executor{svc: caller, host: Hostname}
}

// ForHost returns a copy of the executor with a different hostname to be applied to requests.
func (_c Executor) ForHost(host string) Executor {
	return Executor{svc: _c.svc, host: host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithOptions returns a copy of the executor with options to be applied to requests.
func (_c Executor) WithOptions(opts ...pub.Option) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: append(_c.opts, opts...), inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithInputFlow returns a copy of the executor with an input flow to use for task execution.
// The input flow's state is available to the task in addition to the typed input arguments.
func (_c Executor) WithInputFlow(flow *workflow.RawFlow) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: flow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithOutputFlow returns a copy of the executor with an output flow to populate after task execution.
// The output flow captures the full flow state including control signals (Goto, Retry, Interrupt, Sleep).
func (_c Executor) WithOutputFlow(flow *workflow.Flow) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: flow, runner: _c.runner, flowOptions: _c.flowOptions}
}

// WithWorkflowRunner returns a copy of the executor with a workflow runner for executing workflows.
// foremanapi.NewClient(svc) satisfies the WorkflowRunner interface.
func (_c Executor) WithWorkflowRunner(runner WorkflowRunner) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: runner, flowOptions: _c.flowOptions}
}

// WithFlowOptions returns a copy of the executor that creates workflows with the given flow options
// (priority, fairness key and weight). It has no effect on task execution.
func (_c Executor) WithFlowOptions(flowOptions *workflow.FlowOptions) Executor {
	return Executor{svc: _c.svc, host: _c.host, opts: _c.opts, inFlow: _c.inFlow, outFlow: _c.outFlow, runner: _c.runner, flowOptions: flowOptions}
}

// Subgraph runs this microservice's workflows from inside a task body. Create it with
// NewSubgraph(flow), then call the method named after the workflow you want to invoke.
type Subgraph struct {
	flow *workflow.Flow
}

// NewSubgraph creates a subgraph client bound to the calling task's flow carrier.
func NewSubgraph(flow *workflow.Flow) Subgraph {
	return Subgraph{flow: flow}
}

// marshalTask supports task execution via the Executor.
func marshalTask(ctx context.Context, svc service.Publisher, opts []pub.Option, host string, method string, route string, in any, out any, inFlow *workflow.RawFlow, outFlow *workflow.Flow) (err error) {
	flow := inFlow
	if flow == nil {
		flow = workflow.NewRawFlow()
	}
	inState, err := workflow.NewState(in)
	if err != nil {
		return errors.Trace(err)
	}
	state := flow.RawState()
	err = state.Merge(inState)
	if err != nil {
		return errors.Trace(err)
	}
	flow.SetRawState(state)
	body, err := json.Marshal(flow)
	if err != nil {
		return errors.Trace(err)
	}
	u := httpx.JoinHostAndPath(host, route)
	httpRes, err := svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(u),
		pub.Body(body),
		pub.ContentType("application/json"),
		pub.Options(opts...),
	)
	if err != nil {
		return err // No trace
	}
	err = json.NewDecoder(httpRes.Body).Decode(flow)
	if err != nil {
		return errors.Trace(err)
	}
	if outFlow != nil {
		*outFlow = flow.Flow
	}
	if out != nil {
		err = flow.ParseState(out)
		return errors.Trace(err)
	}
	return nil
}

// marshalWorkflow supports workflow execution via the Executor.
func marshalWorkflow(ctx context.Context, runner WorkflowRunner, flowOptions *workflow.FlowOptions, workflowURL string, in any, out any) (status string, err error) {
	outcome, err := runner.Run(ctx, workflowURL, in, flowOptions)
	if err != nil {
		if outcome != nil {
			return outcome.Status, err // No trace
		}
		return "", err // No trace
	}
	if outcome == nil {
		return "", nil
	}
	status = outcome.Status
	if out != nil {
		err = outcome.State.Parse(out)
		if err != nil {
			return status, errors.Trace(err)
		}
	}
	return status, nil
}

// marshalSubgraph runs a child workflow via the flow carrier and returns the parker's yield.
func marshalSubgraph(flow *workflow.Flow, url string, in any, out any) (yield bool, err error) {
	if flow == nil {
		return false, errors.New("Subgraph requires a flow carrier (call from a task body)")
	}
	return flow.Subgraph(url, in, out)
}

// Demo serves the demo page for the credit approval workflow.
func (_c Client) Demo(ctx context.Context, method string, relativeURL string, body any) (res *http.Response, err error) { // MARKER: Demo
	if method == "" {
		method = Demo.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Request(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Demo.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// Demo serves the demo page for the credit approval workflow.
func (_c MulticastClient) Demo(ctx context.Context, method string, relativeURL string, body any) iter.Seq[*pub.Response] { // MARKER: Demo
	if method == "" {
		method = Demo.Method
	}
	if method == "ANY" {
		method = "POST"
	}
	return _c.svc.Publish(
		ctx,
		pub.Method(method),
		pub.URL(httpx.JoinHostAndPath(_c.host, Demo.Route)),
		pub.RelativeURL(relativeURL),
		pub.Body(body),
		pub.Options(_c.opts...),
	)
}

// SubmitCreditApplication receives a credit application and unpacks the applicant into individual workflow
// state fields.
func (_c Executor) SubmitCreditApplication(ctx context.Context, applicant Applicant) (applicantName string, ssn string, address string, phone string, employers []string, creditScore int, err error) { // MARKER: SubmitCreditApplication
	var out SubmitCreditApplicationOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, SubmitCreditApplication.Method, SubmitCreditApplication.Route, SubmitCreditApplicationIn{Applicant: applicant}, &out, _c.inFlow, _c.outFlow)
	return out.ApplicantName, out.SSN, out.Address, out.Phone, out.Employers, out.CreditScore, err // No trace
}

// VerifyCredit checks the applicant's credit score.
func (_c Executor) VerifyCredit(ctx context.Context, creditScore int) (creditVerified bool, err error) { // MARKER: VerifyCredit
	var out VerifyCreditOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, VerifyCredit.Method, VerifyCredit.Route, VerifyCreditIn{CreditScore: creditScore}, &out, _c.inFlow, _c.outFlow)
	return out.CreditVerified, err // No trace
}

// VerifyEmployment checks the applicant's employment status.
func (_c Executor) VerifyEmployment(ctx context.Context, applicantName string, employerName string) (employmentFailuresOut int, err error) { // MARKER: VerifyEmployment
	var out VerifyEmploymentOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, VerifyEmployment.Method, VerifyEmployment.Route, VerifyEmploymentIn{ApplicantName: applicantName, EmployerName: employerName}, &out, _c.inFlow, _c.outFlow)
	return out.EmploymentFailuresOut, err // No trace
}

// InitIdentityVerification is the entry point for the identity verification subgraph.
func (_c Executor) InitIdentityVerification(ctx context.Context, applicantName string, ssn string, address string, phone string) (err error) { // MARKER: InitIdentityVerification
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, InitIdentityVerification.Method, InitIdentityVerification.Route, InitIdentityVerificationIn{ApplicantName: applicantName, SSN: ssn, Address: address, Phone: phone}, nil, _c.inFlow, _c.outFlow)
	return err // No trace
}

// VerifySSN checks the applicant's SSN.
func (_c Executor) VerifySSN(ctx context.Context, ssn string) (ssnVerified bool, err error) { // MARKER: VerifySSN
	var out VerifySSNOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, VerifySSN.Method, VerifySSN.Route, VerifySSNIn{SSN: ssn}, &out, _c.inFlow, _c.outFlow)
	return out.SsnVerified, err // No trace
}

// VerifyAddress checks the applicant's address.
func (_c Executor) VerifyAddress(ctx context.Context, address string) (addressVerified bool, err error) { // MARKER: VerifyAddress
	var out VerifyAddressOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, VerifyAddress.Method, VerifyAddress.Route, VerifyAddressIn{Address: address}, &out, _c.inFlow, _c.outFlow)
	return out.AddressVerified, err // No trace
}

// VerifyPhoneNumber checks the applicant's phone number.
func (_c Executor) VerifyPhoneNumber(ctx context.Context, phone string) (phoneVerified bool, err error) { // MARKER: VerifyPhoneNumber
	var out VerifyPhoneNumberOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, VerifyPhoneNumber.Method, VerifyPhoneNumber.Route, VerifyPhoneNumberIn{Phone: phone}, &out, _c.inFlow, _c.outFlow)
	return out.PhoneVerified, err // No trace
}

// IdentityDecision determines whether the applicant's identity is verified based on SSN, address, and phone checks.
func (_c Executor) IdentityDecision(ctx context.Context, ssnVerified bool, addressVerified bool, phoneVerified bool) (identityVerified bool, err error) { // MARKER: IdentityDecision
	var out IdentityDecisionOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, IdentityDecision.Method, IdentityDecision.Route, IdentityDecisionIn{SsnVerified: ssnVerified, AddressVerified: addressVerified, PhoneVerified: phoneVerified}, &out, _c.inFlow, _c.outFlow)
	return out.IdentityVerified, err // No trace
}

// RunIdentityVerification invokes the IdentityVerification subgraph via flow.Subgraph and adopts identityVerified.
func (_c Executor) RunIdentityVerification(ctx context.Context, applicantName string, ssn string, address string, phone string) (identityVerified bool, err error) { // MARKER: RunIdentityVerification
	var out RunIdentityVerificationOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, RunIdentityVerification.Method, RunIdentityVerification.Route, RunIdentityVerificationIn{ApplicantName: applicantName, SSN: ssn, Address: address, Phone: phone}, &out, _c.inFlow, _c.outFlow)
	return out.IdentityVerified, err // No trace
}

// RequestMoreInfo requests additional information for the credit review and increments the review attempt counter.
func (_c Executor) RequestMoreInfo(ctx context.Context, reviewAttempts int) (reviewAttemptsOut int, err error) { // MARKER: RequestMoreInfo
	var out RequestMoreInfoOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, RequestMoreInfo.Method, RequestMoreInfo.Route, RequestMoreInfoIn{ReviewAttempts: reviewAttempts}, &out, _c.inFlow, _c.outFlow)
	return out.ReviewAttemptsOut, err // No trace
}

// ReviewCredit performs a manual review of borderline credit scores. For very borderline scores (550-579)
// it requests more info up to 2 times before deciding; scores of 580+ are approved and below 550 are
// rejected.
func (_c Executor) ReviewCredit(ctx context.Context, creditScore int, creditVerified bool, reviewAttempts int) (creditVerifiedOut bool, err error) { // MARKER: ReviewCredit
	var out ReviewCreditOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, ReviewCredit.Method, ReviewCredit.Route, ReviewCreditIn{CreditScore: creditScore, CreditVerified: creditVerified, ReviewAttempts: reviewAttempts}, &out, _c.inFlow, _c.outFlow)
	return out.CreditVerifiedOut, err // No trace
}

// HandleCreditError handles a credit verification error by setting creditVerified to false.
func (_c Executor) HandleCreditError(ctx context.Context, onErr *errors.TracedError) (creditVerified bool, err error) { // MARKER: HandleCreditError
	var out HandleCreditErrorOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, HandleCreditError.Method, HandleCreditError.Route, HandleCreditErrorIn{OnErr: onErr}, &out, _c.inFlow, _c.outFlow)
	return out.CreditVerified, err // No trace
}

// Decision determines whether to approve the credit application based on verification results.
func (_c Executor) Decision(ctx context.Context, creditVerified bool, employmentFailures int, identityVerified bool) (approved bool, err error) { // MARKER: Decision
	var out DecisionOut
	err = marshalTask(ctx, _c.svc, _c.opts, _c.host, Decision.Method, Decision.Route, DecisionIn{CreditVerified: creditVerified, EmploymentFailures: employmentFailures, IdentityVerified: identityVerified}, &out, _c.inFlow, _c.outFlow)
	return out.Approved, err // No trace
}

// IdentityVerification defines the workflow graph for the identity verification process.
func (_c Executor) IdentityVerification(ctx context.Context, applicantName string, ssn string, address string, phone string) (identityVerified bool, status string, err error) { // MARKER: IdentityVerification
	if _c.runner == nil {
		return identityVerified, "", errors.New("workflow runner not set, use WithWorkflowRunner")
	}
	var out IdentityVerificationOut
	status, err = marshalWorkflow(ctx, _c.runner, _c.flowOptions, IdentityVerification.URL(), IdentityVerificationIn{ApplicantName: applicantName, SSN: ssn, Address: address, Phone: phone}, &out)
	return out.IdentityVerified, status, err
}

// IdentityVerification defines the workflow graph for the identity verification process.
func (_sg Subgraph) IdentityVerification(ctx context.Context, applicantName string, ssn string, address string, phone string) (identityVerified bool, yield bool, err error) { // MARKER: IdentityVerification
	var out IdentityVerificationOut
	yield, err = marshalSubgraph(_sg.flow, IdentityVerification.URL(), IdentityVerificationIn{ApplicantName: applicantName, SSN: ssn, Address: address, Phone: phone}, &out)
	if yield || err != nil {
		return identityVerified, yield, err
	}
	return out.IdentityVerified, false, nil
}

// CreditApproval defines the workflow graph for the full credit approval process.
func (_c Executor) CreditApproval(ctx context.Context, applicant Applicant) (approved bool, creditVerified bool, employmentFailures int, identityVerified bool, status string, err error) { // MARKER: CreditApproval
	if _c.runner == nil {
		return approved, creditVerified, employmentFailures, identityVerified, "", errors.New("workflow runner not set, use WithWorkflowRunner")
	}
	var out CreditApprovalOut
	status, err = marshalWorkflow(ctx, _c.runner, _c.flowOptions, CreditApproval.URL(), CreditApprovalIn{Applicant: applicant}, &out)
	return out.Approved, out.CreditVerified, out.EmploymentFailures, out.IdentityVerified, status, err
}

// CreditApproval defines the workflow graph for the full credit approval process.
func (_sg Subgraph) CreditApproval(ctx context.Context, applicant Applicant) (approved bool, creditVerified bool, employmentFailures int, identityVerified bool, yield bool, err error) { // MARKER: CreditApproval
	var out CreditApprovalOut
	yield, err = marshalSubgraph(_sg.flow, CreditApproval.URL(), CreditApprovalIn{Applicant: applicant}, &out)
	if yield || err != nil {
		return approved, creditVerified, employmentFailures, identityVerified, yield, err
	}
	return out.Approved, out.CreditVerified, out.EmploymentFailures, out.IdentityVerified, false, nil
}
