/*
Copyright (c) 2023-2024 Microbus LLC and various contributors

This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
Neither may be used, copied or distributed without the express written consent of Microbus LLC.
*/

// Code generated by Microbus. DO NOT EDIT.

package inbox

const Version = 112
const SourceCodeSHA256 = "3fc5820ebb9d56a6fd06c5b52a12bc3e2b2e59ed3c1c909db9022fbc9af535df"
const Timestamp = "2024-06-12T04:08:52.730775Z"

/* {
	"ver": 112,
	"sha256": "3fc5820ebb9d56a6fd06c5b52a12bc3e2b2e59ed3c1c909db9022fbc9af535df",
	"ts": "2024-06-12T04:08:52.730775Z"
} */
