// Code generated by Microbus. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	"github.com/microbus-io/fabric/application"

	"github.com/microbus-io/fabric/coreservices/smtpingress"
)

// main runs an app containing only the smtp.ingress.sys service.
func main() {
	app := application.New()
	app.Include(smtpingress.NewService())
	err := app.Run()
	if err != nil {
		fmt.Fprintf(os.Stderr, "%+v", err)
		os.Exit(19)
	}
}
